// Generated by stratus_hls 19.12-s100  (91710.131054)
// Tue Apr 12 21:28:35 2022
// from ../GaussFilter.cpp

`timescale 1ps / 1ps

      
module GaussFilter_ROM_9X32_mask(in1, out1, clk);

      input [3:0] in1;
      input clk;
      output [31:0] out1;
      reg [31:0] out1;
      reg[31:0] mask[8:0];

         initial begin
            $readmemh("bdw_work/modules/GaussFilter/PIPE/GaussFilter_ROM_9X32_mask_0.memh", mask);
         end

         always @(posedge clk)
          begin :GaussFilter_ROM_9X32_mask_mask_thread_1
            if (in1 < 4'd09) begin
               out1 <= mask[in1];
            end
         end


endmodule

