// Generated by stratus_hls 19.12-s100  (91710.131054)
// Tue Apr 12 21:25:06 2022
// from ../GaussFilter.cpp
#ifndef CYNTH_PART_GaussFilter_GaussFilter_rtl_h
#define CYNTH_PART_GaussFilter_GaussFilter_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "GaussFilter_ROM_9X32_mask.h"


/* Declaration of the synthesized module. */
struct GaussFilter : public sc_module {
  sc_in<bool > i_clk;
  sc_in<bool > i_rst;
  sc_out<bool > i_rgb_busy;
  sc_in<bool > i_rgb_vld;
  sc_in<sc_uint<24> > i_rgb_data;
  sc_in<bool > o_rgb_busy;
  sc_out<bool > o_rgb_vld;
  sc_out<sc_uint<24> > o_rgb_data;
  GaussFilter( sc_module_name name );
  SC_HAS_PROCESS(GaussFilter);
  sc_signal<bool > o_rgb_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > GaussFilter_Xor_1Ux1U_1U_1_1_out1;
  sc_signal<bool > o_rgb_m_unacked_req;
  sc_signal<sc_uint<1> > GaussFilter_Or_1Ux1U_1U_4_2_out1;
  sc_signal<sc_uint<1> > GaussFilter_N_Muxb_1_2_14_4_4_out1;
  sc_signal<bool > i_rgb_m_unvalidated_req;
  sc_signal<sc_uint<1> > 
  GaussFilter_gen_busy_r_4_34_gen_busy_i_rgb_m_data_is_invalid_next;
  sc_signal<sc_uint<1> > GaussFilter_gen_busy_r_4_34_gdiv;
  sc_signal<sc_uint<1> > GaussFilter_gen_busy_r_4_34_gnew_req;
  sc_signal<sc_uint<3> > global_state_next;
  sc_signal<sc_uint<1> > GaussFilter_Lti255s29_4_14_out1;
  sc_signal<sc_uint<29> > GaussFilter_N_Mux_29_2_19_4_13_out1;
  sc_signal<sc_uint<1> > GaussFilter_N_Mux_29_2_19_4_13_ctrl1;
  sc_signal<sc_int<29> > GaussFilter_Add_28Sx1U_29S_4_12_out1;
  sc_signal<sc_int<28> > GaussFilter_Add_28Sx1U_29S_4_12_in2;
  sc_signal<sc_uint<1> > GaussFilter_And_1Ux1U_1U_4_11_out1;
  sc_signal<sc_uint<1> > GaussFilter_And_1Ux1U_1U_4_11_in1;
  sc_signal<sc_uint<1> > GaussFilter_OrReduction_4U_1U_4_10_out1;
  sc_signal<sc_int<32> > GaussFilter_Add2Mul2s32u8s32_4_9_in1;
  sc_signal<sc_uint<1> > gs_ctrl2;
  sc_signal<sc_uint<8> > GaussFilter_Add2Mul2s32u8s32_4_9_in2;
  sc_signal<sc_int<32> > GaussFilter_Add2Mul2s32u8s32_4_9_in3;
  sc_signal<sc_uint<2> > gs_ctrl0;
  sc_signal<sc_uint<4> > GaussFilter_Add2u2Mul2i3u2_4_6_out1;
  sc_signal<sc_uint<32> > s_reg_23;
  sc_signal<sc_uint<2> > GaussFilter_Add2i1u2_4_8_out1;
  sc_signal<sc_uint<2> > GaussFilter_Add2i1u2_4_7_out1;
  sc_signal<sc_uint<2> > s_reg_21;
  sc_signal<sc_uint<32> > s_reg_20;
  sc_signal<sc_uint<32> > s_reg_19;
  sc_signal<sc_int<32> > GaussFilter_Add2Mul2s32u8s32_4_9_out1;
  sc_signal<sc_uint<32> > s_reg_18;
  sc_signal<sc_uint<2> > s_reg_22;
  sc_signal<sc_uint<2> > s_reg_17;
  sc_signal<sc_uint<3> > GaussFilter_gen_busy_r_4_34_out1;
  sc_signal<sc_uint<1> > GaussFilter_And_1Ux1U_1U_4_32_out1;
  sc_signal<sc_uint<1> > GaussFilter_Not_1U_1U_1_3_out1;
  sc_signal<bool > o_rgb_m_req_m_trig_req;
  sc_signal<bool > i_rgb_m_busy_req_0;
  sc_signal<sc_uint<8> > GaussFilter_N_Mux_8_2_20_4_15_out1;
  sc_signal<sc_uint<8> > s_reg_25;
  sc_signal<sc_uint<8> > s_reg_24;
  sc_signal<sc_uint<1> > GaussFilter_Lti3u2_4_23_out1;
  sc_signal<sc_uint<1> > GaussFilter_Lti3u2_4_31_out1;
  sc_signal<sc_uint<3> > global_state;
  sc_signal<sc_uint<1> > stall0;
  sc_signal<sc_uint<4> > mask_in1;
  sc_signal<sc_uint<32> > mask_out1;
  GaussFilter_ROM_9X32_mask *mask;
  void drive_o_rgb_data();
  void drive_i_rgb_m_busy_req_0();
  void drive_o_rgb_m_req_m_trig_req();
  void drive_stall0();
  void drive_s_reg_17();
  void drive_s_reg_18();
  void drive_s_reg_19();
  void drive_s_reg_20();
  void drive_s_reg_21();
  void drive_s_reg_22();
  void drive_s_reg_23();
  void drive_s_reg_24();
  void drive_s_reg_25();
  void GaussFilter_Add2u2Mul2i3u2_4_6();
  void GaussFilter_Add2i1u2_4_7();
  void GaussFilter_Add2i1u2_4_8();
  void drive_mask_in1();
  void drive_GaussFilter_Add2Mul2s32u8s32_4_9_in3();
  void drive_GaussFilter_Add2Mul2s32u8s32_4_9_in2();
  void drive_GaussFilter_Add2Mul2s32u8s32_4_9_in1();
  void GaussFilter_Add2Mul2s32u8s32_4_9();
  void GaussFilter_OrReduction_4U_1U_4_10();
  void drive_GaussFilter_And_1Ux1U_1U_4_11_in1();
  void GaussFilter_And_1Ux1U_1U_4_11();
  void drive_GaussFilter_Add_28Sx1U_29S_4_12_in2();
  void GaussFilter_Add_28Sx1U_29S_4_12();
  void drive_GaussFilter_N_Mux_29_2_19_4_13_ctrl1();
  void GaussFilter_N_Mux_29_2_19_4_13();
  void GaussFilter_Lti255s29_4_14();
  void GaussFilter_N_Mux_8_2_20_4_15();
  void GaussFilter_Lti3u2_4_23();
  void GaussFilter_Lti3u2_4_31();
  void drive_global_state();
  void drive_global_state_next();
  void drive_gs_ctrl0();
  void drive_gs_ctrl2();
  void drive_i_rgb_busy();
  void GaussFilter_gen_busy_r_4_34_p8();
  void GaussFilter_gen_busy_r_4_34_p7();
  void GaussFilter_gen_busy_r_4_34_p6();
  void GaussFilter_gen_busy_r_4_34_p5();
  void drive_i_rgb_m_unvalidated_req();
  void GaussFilter_N_Muxb_1_2_14_4_4();
  void drive_o_rgb_vld();
  void GaussFilter_Or_1Ux1U_1U_4_2();
  void drive_o_rgb_m_unacked_req();
  void GaussFilter_And_1Ux1U_1U_4_32();
  void GaussFilter_Xor_1Ux1U_1U_1_1();
  void drive_o_rgb_m_req_m_prev_trig_req();
  void GaussFilter_Not_1U_1U_1_3();
};

#endif
