`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:20:34 CST (Apr 12 2022 13:20:34 UTC)

module GaussFilter_Add_4U_8_4(in1, out1);
  input [3:0] in1;
  output [3:0] out1;
  wire [3:0] in1;
  wire [3:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  assign out1[3] = in1[3];
endmodule

