`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:47:14 CST (Apr 12 2022 06:47:14 UTC)

module GaussFilter_Mul_3Ux2U_5U_1(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3, mul_22_8_n_4,
       mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7, mul_22_8_n_8;
  wire mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_12, mul_22_8_n_14,
       mul_22_8_n_16;
  XOR2XL mul_22_8_g131(.A (mul_22_8_n_3), .B (mul_22_8_n_16), .Y
       (out1[3]));
  AOI21X1 mul_22_8_g132(.A0 (mul_22_8_n_7), .A1 (mul_22_8_n_14), .B0
       (mul_22_8_n_3), .Y (out1[4]));
  AOI21X1 mul_22_8_g133(.A0 (mul_22_8_n_8), .A1 (mul_22_8_n_10), .B0
       (mul_22_8_n_6), .Y (mul_22_8_n_16));
  NAND2X1 mul_22_8_g135(.A (mul_22_8_n_8), .B (mul_22_8_n_10), .Y
       (mul_22_8_n_14));
  NOR2BX1 mul_22_8_g137(.AN (mul_22_8_n_8), .B (mul_22_8_n_6), .Y
       (mul_22_8_n_12));
  NOR2BX1 mul_22_8_g138(.AN (mul_22_8_n_9), .B (mul_22_8_n_10), .Y
       (out1[1]));
  NOR2X4 mul_22_8_g139(.A (mul_22_8_n_2), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_10));
  NAND2X1 mul_22_8_g140(.A (mul_22_8_n_2), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_9));
  NAND2X4 mul_22_8_g141(.A (mul_22_8_n_1), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_8));
  INVX1 mul_22_8_g142(.A (mul_22_8_n_6), .Y (mul_22_8_n_7));
  NOR2X1 mul_22_8_g143(.A (mul_22_8_n_1), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_6));
  NAND2X4 mul_22_8_g144(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_5));
  NAND2X6 mul_22_8_g145(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_4));
  NAND2X1 mul_22_8_g146(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_3));
  NAND2X4 mul_22_8_g148(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_2));
  NAND2X8 mul_22_8_g149(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_1));
  AND2X1 mul_22_8_g2(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  XOR2XL mul_22_8_g152(.A (mul_22_8_n_10), .B (mul_22_8_n_12), .Y
       (out1[2]));
endmodule


