`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:12 CST (Apr 12 2022 13:35:12 UTC)

module GaussFilter_NotEQ_2Ux1U_1U_4(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output out1;
  wire [1:0] in2;
  wire in1;
  wire out1;
  wire n_0, n_1, n_2;
  OAI221X1 g17(.A0 (n_1), .A1 (in1), .B0 (n_2), .B1 (in2[0]), .C0
       (n_0), .Y (out1));
  INVX1 g18(.A (in1), .Y (n_2));
  INVX1 g20(.A (in2[0]), .Y (n_1));
  INVX1 g19(.A (in2[1]), .Y (n_0));
endmodule


