`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:51:43 CST (Apr 12 2022 06:51:43 UTC)

module GaussFilter_Mul_5U_11_1(in1, out1);
  input [2:0] in1;
  output [4:0] out1;
  wire [2:0] in1;
  wire [4:0] out1;
  wire const_mul_20_8_n_0, const_mul_20_8_n_1, const_mul_20_8_n_2,
       const_mul_20_8_n_3, const_mul_20_8_n_4, const_mul_20_8_n_5,
       const_mul_20_8_n_7, const_mul_20_8_n_8;
  wire const_mul_20_8_n_10, const_mul_20_8_n_11;
  assign out1[0] = in1[0];
  MXI2XL const_mul_20_8_g106(.A (const_mul_20_8_n_1), .B (in1[2]), .S0
       (const_mul_20_8_n_11), .Y (out1[3]));
  NOR2X1 const_mul_20_8_g107(.A (const_mul_20_8_n_1), .B
       (const_mul_20_8_n_10), .Y (out1[4]));
  OAI21X2 const_mul_20_8_g108(.A0 (const_mul_20_8_n_2), .A1
       (const_mul_20_8_n_3), .B0 (const_mul_20_8_n_5), .Y
       (const_mul_20_8_n_11));
  NOR2BX1 const_mul_20_8_g109(.AN (const_mul_20_8_n_5), .B
       (const_mul_20_8_n_8), .Y (const_mul_20_8_n_10));
  MXI2X1 const_mul_20_8_g110(.A (const_mul_20_8_n_7), .B
       (const_mul_20_8_n_2), .S0 (const_mul_20_8_n_0), .Y (out1[2]));
  NOR2X1 const_mul_20_8_g111(.A (const_mul_20_8_n_2), .B
       (const_mul_20_8_n_3), .Y (const_mul_20_8_n_8));
  INVX1 const_mul_20_8_g112(.A (const_mul_20_8_n_2), .Y
       (const_mul_20_8_n_7));
  NOR2X1 const_mul_20_8_g114(.A (const_mul_20_8_n_7), .B
       (const_mul_20_8_n_4), .Y (out1[1]));
  NAND2X2 const_mul_20_8_g115(.A (in1[2]), .B (in1[1]), .Y
       (const_mul_20_8_n_5));
  NOR2X1 const_mul_20_8_g116(.A (in1[1]), .B (in1[0]), .Y
       (const_mul_20_8_n_4));
  NOR2X8 const_mul_20_8_g118(.A (in1[2]), .B (in1[1]), .Y
       (const_mul_20_8_n_3));
  NAND2X6 const_mul_20_8_g120(.A (in1[1]), .B (in1[0]), .Y
       (const_mul_20_8_n_2));
  INVX1 const_mul_20_8_g121(.A (in1[2]), .Y (const_mul_20_8_n_1));
  NAND2BX1 const_mul_20_8_g2(.AN (const_mul_20_8_n_3), .B
       (const_mul_20_8_n_5), .Y (const_mul_20_8_n_0));
endmodule


