`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:25 CST (Apr 12 2022 13:35:25 UTC)

module GaussFilter_Mul_8Ux3S_11S_1(in2, in1, out1);
  input [7:0] in2;
  input [2:0] in1;
  output [10:0] out1;
  wire [7:0] in2;
  wire [2:0] in1;
  wire [10:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_10;
  wire mul_22_8_n_12, mul_22_8_n_13, mul_22_8_n_15, mul_22_8_n_16,
       mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19, mul_22_8_n_20;
  wire mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24,
       mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27, mul_22_8_n_28;
  wire mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32,
       mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_36, mul_22_8_n_37;
  wire mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40, mul_22_8_n_41,
       mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45;
  wire mul_22_8_n_46, mul_22_8_n_48, mul_22_8_n_49, mul_22_8_n_50,
       mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_53, mul_22_8_n_54;
  wire mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_57, mul_22_8_n_58,
       mul_22_8_n_59, mul_22_8_n_60, mul_22_8_n_61, mul_22_8_n_62;
  wire mul_22_8_n_63, mul_22_8_n_64, mul_22_8_n_65, mul_22_8_n_66,
       mul_22_8_n_67, mul_22_8_n_68, mul_22_8_n_69, mul_22_8_n_70;
  wire mul_22_8_n_71, mul_22_8_n_72, mul_22_8_n_73, mul_22_8_n_74,
       mul_22_8_n_75, mul_22_8_n_76, mul_22_8_n_77, mul_22_8_n_78;
  wire mul_22_8_n_80, mul_22_8_n_81, mul_22_8_n_82, mul_22_8_n_84,
       mul_22_8_n_86, mul_22_8_n_87, mul_22_8_n_88, mul_22_8_n_89;
  wire mul_22_8_n_90, mul_22_8_n_92, mul_22_8_n_107, mul_22_8_n_109,
       mul_22_8_n_112, mul_22_8_n_113, mul_22_8_n_114, mul_22_8_n_115;
  wire mul_22_8_n_116, mul_22_8_n_117, mul_22_8_n_119, mul_22_8_n_121,
       mul_22_8_n_122, mul_22_8_n_124, mul_22_8_n_125;
  AOI21X1 mul_22_8_g662(.A0 (mul_22_8_n_48), .A1 (mul_22_8_n_92), .B0
       (mul_22_8_n_49), .Y (out1[10]));
  MXI2XL mul_22_8_g665(.A (mul_22_8_n_68), .B (mul_22_8_n_69), .S0
       (mul_22_8_n_90), .Y (out1[7]));
  OAI21X2 mul_22_8_g666(.A0 (mul_22_8_n_56), .A1 (mul_22_8_n_88), .B0
       (mul_22_8_n_55), .Y (mul_22_8_n_92));
  MXI2XL mul_22_8_g667(.A (mul_22_8_n_72), .B (mul_22_8_n_73), .S0
       (mul_22_8_n_107), .Y (out1[8]));
  NOR2X1 mul_22_8_g668(.A (mul_22_8_n_2), .B (mul_22_8_n_89), .Y
       (mul_22_8_n_90));
  NOR2XL mul_22_8_g671(.A (mul_22_8_n_70), .B (mul_22_8_n_87), .Y
       (mul_22_8_n_89));
  NOR2X1 mul_22_8_g672(.A (mul_22_8_n_10), .B (mul_22_8_n_82), .Y
       (mul_22_8_n_88));
  AOI21X1 mul_22_8_g673(.A0 (mul_22_8_n_74), .A1 (mul_22_8_n_115), .B0
       (mul_22_8_n_80), .Y (mul_22_8_n_87));
  AOI21X1 mul_22_8_g674(.A0 (mul_22_8_n_4), .A1 (mul_22_8_n_113), .B0
       (mul_22_8_n_66), .Y (mul_22_8_n_86));
  ADDFHX1 mul_22_8_g678(.A (mul_22_8_n_109), .B (mul_22_8_n_61), .CI
       (mul_22_8_n_78), .CO (mul_22_8_n_84), .S (out1[3]));
  OAI2BB1X1 mul_22_8_g679(.A0N (mul_22_8_n_77), .A1N (mul_22_8_n_80),
       .B0 (mul_22_8_n_81), .Y (mul_22_8_n_82));
  AOI21X2 mul_22_8_g680(.A0 (mul_22_8_n_2), .A1 (mul_22_8_n_58), .B0
       (mul_22_8_n_3), .Y (mul_22_8_n_81));
  OAI21X1 mul_22_8_g681(.A0 (mul_22_8_n_65), .A1 (mul_22_8_n_71), .B0
       (mul_22_8_n_67), .Y (mul_22_8_n_80));
  ADDFX1 mul_22_8_g682(.A (mul_22_8_n_41), .B (mul_22_8_n_27), .CI
       (mul_22_8_n_46), .CO (mul_22_8_n_78), .S (out1[2]));
  NOR2X1 mul_22_8_g684(.A (mul_22_8_n_70), .B (mul_22_8_n_57), .Y
       (mul_22_8_n_77));
  NOR2XL mul_22_8_g686(.A (mul_22_8_n_2), .B (mul_22_8_n_70), .Y
       (mul_22_8_n_76));
  NOR2BX1 mul_22_8_g688(.AN (mul_22_8_n_67), .B (mul_22_8_n_119), .Y
       (mul_22_8_n_75));
  INVX1 mul_22_8_g691(.A (mul_22_8_n_6), .Y (mul_22_8_n_74));
  INVX1 mul_22_8_g693(.A (mul_22_8_n_72), .Y (mul_22_8_n_73));
  NOR2BX1 mul_22_8_g694(.AN (mul_22_8_n_55), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_72));
  NOR2X2 mul_22_8_g696(.A (mul_22_8_n_59), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_71));
  NOR2X1 mul_22_8_g697(.A (mul_22_8_n_63), .B (mul_22_8_n_52), .Y
       (mul_22_8_n_70));
  INVX1 mul_22_8_g698(.A (mul_22_8_n_68), .Y (mul_22_8_n_69));
  NOR2X1 mul_22_8_g699(.A (mul_22_8_n_3), .B (mul_22_8_n_57), .Y
       (mul_22_8_n_68));
  NAND2XL mul_22_8_g703(.A (mul_22_8_n_59), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_67));
  INVX1 mul_22_8_g704(.A (mul_22_8_n_65), .Y (mul_22_8_n_66));
  NAND2X2 mul_22_8_g705(.A (mul_22_8_n_62), .B (mul_22_8_n_60), .Y
       (mul_22_8_n_65));
  ADDFX1 mul_22_8_g706(.A (mul_22_8_n_26), .B (mul_22_8_n_24), .CI
       (mul_22_8_n_22), .CO (mul_22_8_n_63), .S (mul_22_8_n_64));
  ADDFHXL mul_22_8_g708(.A (mul_22_8_n_33), .B (mul_22_8_n_25), .CI
       (mul_22_8_n_12), .CO (mul_22_8_n_62), .S (mul_22_8_n_61));
  ADDFXL mul_22_8_g710(.A (mul_22_8_n_34), .B (mul_22_8_n_21), .CI
       (mul_22_8_n_13), .CO (mul_22_8_n_59), .S (mul_22_8_n_60));
  INVX1 mul_22_8_g711(.A (mul_22_8_n_57), .Y (mul_22_8_n_58));
  NOR2X2 mul_22_8_g712(.A (mul_22_8_n_51), .B (mul_22_8_n_54), .Y
       (mul_22_8_n_57));
  NOR2X1 mul_22_8_g713(.A (mul_22_8_n_45), .B (mul_22_8_n_53), .Y
       (mul_22_8_n_56));
  NAND2X1 mul_22_8_g714(.A (mul_22_8_n_45), .B (mul_22_8_n_53), .Y
       (mul_22_8_n_55));
  ADDFHXL mul_22_8_g717(.A (mul_22_8_n_0), .B (mul_22_8_n_30), .CI
       (mul_22_8_n_31), .CO (mul_22_8_n_53), .S (mul_22_8_n_54));
  ADDFX1 mul_22_8_g719(.A (mul_22_8_n_32), .B (mul_22_8_n_23), .CI
       (mul_22_8_n_1), .CO (mul_22_8_n_51), .S (mul_22_8_n_52));
  NOR2BX1 mul_22_8_g721(.AN (mul_22_8_n_48), .B (mul_22_8_n_49), .Y
       (mul_22_8_n_50));
  NOR2X1 mul_22_8_g722(.A (mul_22_8_n_29), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_49));
  NAND2XL mul_22_8_g723(.A (mul_22_8_n_29), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_48));
  AOI21X1 mul_22_8_g724(.A0 (mul_22_8_n_39), .A1 (mul_22_8_n_40), .B0
       (mul_22_8_n_41), .Y (out1[1]));
  NAND2BX1 mul_22_8_g725(.AN (mul_22_8_n_44), .B (mul_22_8_n_43), .Y
       (mul_22_8_n_46));
  XNOR2X1 mul_22_8_g726(.A (mul_22_8_n_37), .B (mul_22_8_n_36), .Y
       (mul_22_8_n_45));
  NOR2X1 mul_22_8_g727(.A (mul_22_8_n_38), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_44));
  NAND2X2 mul_22_8_g728(.A (mul_22_8_n_38), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_43));
  NAND2BX1 mul_22_8_g729(.AN (mul_22_8_n_36), .B (mul_22_8_n_37), .Y
       (mul_22_8_n_42));
  NOR2X1 mul_22_8_g730(.A (mul_22_8_n_39), .B (mul_22_8_n_40), .Y
       (mul_22_8_n_41));
  AND2XL mul_22_8_g732(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X2 mul_22_8_g733(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_40));
  NAND2X2 mul_22_8_g734(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_39));
  NAND2X8 mul_22_8_g735(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_38));
  NAND2X1 mul_22_8_g736(.A (in2[6]), .B (in1[2]), .Y (mul_22_8_n_37));
  NAND2X1 mul_22_8_g737(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_34));
  NAND2X2 mul_22_8_g738(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_33));
  NOR2X2 mul_22_8_g739(.A (mul_22_8_n_17), .B (mul_22_8_n_125), .Y
       (mul_22_8_n_32));
  AND2X1 mul_22_8_g740(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_31));
  NAND2X1 mul_22_8_g741(.A (in2[7]), .B (mul_22_8_n_121), .Y
       (mul_22_8_n_36));
  NAND2X1 mul_22_8_g742(.A (in2[5]), .B (in1[2]), .Y (mul_22_8_n_30));
  AND2XL mul_22_8_g745(.A (in2[7]), .B (in1[2]), .Y (mul_22_8_n_29));
  NOR2X1 mul_22_8_g746(.A (mul_22_8_n_18), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_27));
  NOR2X4 mul_22_8_g747(.A (mul_22_8_n_16), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_28));
  NAND2X2 mul_22_8_g748(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_26));
  NOR2X2 mul_22_8_g749(.A (mul_22_8_n_18), .B (mul_22_8_n_124), .Y
       (mul_22_8_n_25));
  NOR2X2 mul_22_8_g750(.A (mul_22_8_n_17), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_24));
  NAND2X2 mul_22_8_g752(.A (in2[4]), .B (in1[2]), .Y (mul_22_8_n_23));
  NOR2X1 mul_22_8_g753(.A (mul_22_8_n_15), .B (mul_22_8_n_122), .Y
       (mul_22_8_n_22));
  NOR2X1 mul_22_8_g754(.A (mul_22_8_n_15), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_21));
  CLKINVX4 mul_22_8_g759(.A (in1[0]), .Y (mul_22_8_n_20));
  CLKINVX4 mul_22_8_g760(.A (in1[2]), .Y (mul_22_8_n_19));
  INVX2 mul_22_8_g761(.A (in2[2]), .Y (mul_22_8_n_18));
  INVX3 mul_22_8_g762(.A (in2[5]), .Y (mul_22_8_n_17));
  CLKINVX12 mul_22_8_g763(.A (in2[0]), .Y (mul_22_8_n_16));
  INVX2 mul_22_8_g764(.A (in2[4]), .Y (mul_22_8_n_15));
  AND2X1 mul_22_8_g2(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_13));
  CLKAND2X6 mul_22_8_g766(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_12));
  CLKXOR2X1 mul_22_8_g767(.A (mul_22_8_n_50), .B (mul_22_8_n_92), .Y
       (out1[9]));
  NOR3BX1 mul_22_8_g768(.AN (mul_22_8_n_77), .B (mul_22_8_n_6), .C
       (mul_22_8_n_117), .Y (mul_22_8_n_10));
  XNOR2X1 mul_22_8_g769(.A (mul_22_8_n_76), .B (mul_22_8_n_87), .Y
       (out1[6]));
  XNOR2X1 mul_22_8_g770(.A (mul_22_8_n_75), .B (mul_22_8_n_86), .Y
       (out1[5]));
  XOR2XL mul_22_8_g771(.A (mul_22_8_n_5), .B (mul_22_8_n_112), .Y
       (out1[4]));
  NAND2BX1 mul_22_8_g772(.AN (mul_22_8_n_71), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_6));
  NAND2X1 mul_22_8_g773(.A (mul_22_8_n_4), .B (mul_22_8_n_65), .Y
       (mul_22_8_n_5));
  OR2X1 mul_22_8_g774(.A (mul_22_8_n_62), .B (mul_22_8_n_60), .Y
       (mul_22_8_n_4));
  AND2X1 mul_22_8_g775(.A (mul_22_8_n_51), .B (mul_22_8_n_54), .Y
       (mul_22_8_n_3));
  AND2X1 mul_22_8_g776(.A (mul_22_8_n_63), .B (mul_22_8_n_52), .Y
       (mul_22_8_n_2));
  NOR2BX1 mul_22_8_g777(.AN (in2[6]), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_1));
  NOR2BX2 mul_22_8_g778(.AN (in2[7]), .B (mul_22_8_n_20), .Y
       (mul_22_8_n_0));
  BUFX2 mul_22_8_fopt(.A (mul_22_8_n_88), .Y (mul_22_8_n_107));
  BUFX3 mul_22_8_fopt779(.A (mul_22_8_n_43), .Y (mul_22_8_n_109));
  BUFX2 mul_22_8_fopt780(.A (mul_22_8_n_114), .Y (mul_22_8_n_112));
  INVXL mul_22_8_fopt781(.A (mul_22_8_n_114), .Y (mul_22_8_n_113));
  BUFX2 mul_22_8_fopt782(.A (mul_22_8_n_116), .Y (mul_22_8_n_114));
  INVXL mul_22_8_fopt783(.A (mul_22_8_n_116), .Y (mul_22_8_n_115));
  INVXL mul_22_8_fopt784(.A (mul_22_8_n_84), .Y (mul_22_8_n_116));
  CLKINVX1 mul_22_8_fopt785(.A (mul_22_8_n_84), .Y (mul_22_8_n_117));
  BUFX2 mul_22_8_fopt786(.A (mul_22_8_n_71), .Y (mul_22_8_n_119));
  INVXL mul_22_8_fopt787(.A (mul_22_8_n_122), .Y (mul_22_8_n_121));
  CLKINVX1 mul_22_8_fopt788(.A (in1[1]), .Y (mul_22_8_n_122));
  CLKINVX1 mul_22_8_fopt789(.A (in1[1]), .Y (mul_22_8_n_124));
  CLKINVX1 mul_22_8_fopt790(.A (in1[1]), .Y (mul_22_8_n_125));
endmodule


