`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:13 CST (Apr 12 2022 13:35:13 UTC)

module GaussFilter_Not_1U_1U_4_0(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  INVX1 g2(.A (in1), .Y (out1));
endmodule


