`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:24:56 CST (Apr 12 2022 13:24:56 UTC)

module GaussFilter_Lti255s29_4(in1, out1);
  input [28:0] in1;
  output out1;
  wire [28:0] in1;
  wire out1;
  wire gt_19_99_n_0, gt_19_99_n_1, gt_19_99_n_2, gt_19_99_n_3,
       gt_19_99_n_4, gt_19_99_n_5, gt_19_99_n_6, gt_19_99_n_7;
  wire gt_19_99_n_8, gt_19_99_n_9;
  NAND2BX1 gt_19_99_g546(.AN (in1[28]), .B (gt_19_99_n_9), .Y (out1));
  NAND4XL gt_19_99_g547(.A (gt_19_99_n_3), .B (gt_19_99_n_1), .C
       (gt_19_99_n_8), .D (gt_19_99_n_7), .Y (gt_19_99_n_9));
  NAND4XL gt_19_99_g548(.A (in1[2]), .B (in1[0]), .C (in1[1]), .D
       (gt_19_99_n_6), .Y (gt_19_99_n_8));
  NOR4X1 gt_19_99_g549(.A (in1[28]), .B (gt_19_99_n_4), .C
       (gt_19_99_n_2), .D (gt_19_99_n_0), .Y (gt_19_99_n_7));
  NOR2BX1 gt_19_99_g550(.AN (in1[3]), .B (gt_19_99_n_5), .Y
       (gt_19_99_n_6));
  NAND4XL gt_19_99_g551(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gt_19_99_n_5));
  OR4X1 gt_19_99_g552(.A (in1[27]), .B (in1[26]), .C (in1[25]), .D
       (in1[24]), .Y (gt_19_99_n_4));
  NOR4X1 gt_19_99_g553(.A (in1[15]), .B (in1[14]), .C (in1[13]), .D
       (in1[12]), .Y (gt_19_99_n_3));
  OR4X1 gt_19_99_g554(.A (in1[23]), .B (in1[22]), .C (in1[21]), .D
       (in1[20]), .Y (gt_19_99_n_2));
  NOR4X1 gt_19_99_g555(.A (in1[11]), .B (in1[10]), .C (in1[9]), .D
       (in1[8]), .Y (gt_19_99_n_1));
  OR4X1 gt_19_99_g556(.A (in1[19]), .B (in1[18]), .C (in1[17]), .D
       (in1[16]), .Y (gt_19_99_n_0));
endmodule


