`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 13 2022 07:20:20 CST (Apr 12 2022 23:20:20 UTC)

module GaussFilter_N_Mux_4_6_21_4(ctrl1, out1);
  input [3:0] ctrl1;
  output [3:0] out1;
  wire [3:0] ctrl1;
  wire [3:0] out1;
  wire n_0, n_1;
  assign out1[3] = 1'b0;
  NOR2X1 g21(.A (out1[0]), .B (out1[2]), .Y (out1[1]));
  OAI21X1 g22(.A0 (ctrl1[0]), .A1 (n_1), .B0 (n_0), .Y (out1[0]));
  NOR3BX1 g23(.AN (n_1), .B (ctrl1[3]), .C (ctrl1[0]), .Y (out1[2]));
  NOR2BX1 g24(.AN (ctrl1[2]), .B (ctrl1[1]), .Y (n_1));
  INVX1 g25(.A (ctrl1[3]), .Y (n_0));
endmodule


