`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:50:58 CST (Apr 12 2022 06:50:58 UTC)

module GaussFilter_Add2i1u1_4(in1, out1);
  input in1;
  output [1:0] out1;
  wire in1;
  wire [1:0] out1;
  assign out1[1] = in1;
  INVX1 g4(.A (in1), .Y (out1[0]));
endmodule


