`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:51:46 CST (Apr 12 2022 06:51:46 UTC)

module GaussFilter_Add2i1u1_1(in1, out1);
  input in1;
  output [1:0] out1;
  wire in1;
  wire [1:0] out1;
  assign out1[1] = in1;
  CLKINVX12 g4(.A (in1), .Y (out1[0]));
endmodule


