`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:46:16 CST (Apr 12 2022 06:46:16 UTC)

module GaussFilter_Add_2Ux2U_3U_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [2:0] out1;
  wire [1:0] in2, in1;
  wire [2:0] out1;
  wire add_23_2_n_0;
  ADDFX1 add_23_2_g42(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]), .CO
       (out1[2]), .S (out1[1]));
  ADDHX1 add_23_2_g43(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


