`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:07 CST (Apr 12 2022 13:35:07 UTC)

module GaussFilter_Mul_8Ux4S_12S_4(in2, in1, out1);
  input [7:0] in2;
  input [3:0] in1;
  output [11:0] out1;
  wire [7:0] in2;
  wire [3:0] in1;
  wire [11:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7;
  wire mul_22_8_n_8, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11,
       mul_22_8_n_12, mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_15;
  wire mul_22_8_n_16, mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19,
       mul_22_8_n_20, mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23;
  wire mul_22_8_n_24, mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_28,
       mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32;
  wire mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_36, mul_22_8_n_37,
       mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40, mul_22_8_n_41;
  wire mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45,
       mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49;
  wire mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_54,
       mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_57, mul_22_8_n_58;
  wire mul_22_8_n_59, mul_22_8_n_60, mul_22_8_n_61, mul_22_8_n_62,
       mul_22_8_n_63, mul_22_8_n_64, mul_22_8_n_65, mul_22_8_n_66;
  wire mul_22_8_n_68, mul_22_8_n_69, mul_22_8_n_70, mul_22_8_n_71,
       mul_22_8_n_72, mul_22_8_n_73, mul_22_8_n_74, mul_22_8_n_76;
  wire mul_22_8_n_77, mul_22_8_n_78, mul_22_8_n_79, mul_22_8_n_80,
       mul_22_8_n_81, mul_22_8_n_82, mul_22_8_n_83, mul_22_8_n_84;
  wire mul_22_8_n_86, mul_22_8_n_88, mul_22_8_n_89, mul_22_8_n_90,
       mul_22_8_n_92, mul_22_8_n_94, mul_22_8_n_96;
  INVX1 mul_22_8_g915(.A (mul_22_8_n_96), .Y (out1[11]));
  ADDFX1 mul_22_8_g916(.A (mul_22_8_n_94), .B (mul_22_8_n_46), .CI
       (mul_22_8_n_15), .CO (mul_22_8_n_96), .S (out1[10]));
  ADDFX1 mul_22_8_g917(.A (mul_22_8_n_92), .B (mul_22_8_n_47), .CI
       (mul_22_8_n_56), .CO (mul_22_8_n_94), .S (out1[9]));
  ADDFX1 mul_22_8_g918(.A (mul_22_8_n_90), .B (mul_22_8_n_57), .CI
       (mul_22_8_n_73), .CO (mul_22_8_n_92), .S (out1[8]));
  XNOR2X1 mul_22_8_g919(.A (mul_22_8_n_83), .B (mul_22_8_n_88), .Y
       (out1[7]));
  OAI211X1 mul_22_8_g920(.A0 (mul_22_8_n_70), .A1 (mul_22_8_n_79), .B0
       (mul_22_8_n_89), .C0 (mul_22_8_n_86), .Y (mul_22_8_n_90));
  AOI21XL mul_22_8_g921(.A0 (mul_22_8_n_84), .A1 (mul_22_8_n_81), .B0
       (mul_22_8_n_80), .Y (mul_22_8_n_89));
  OAI21X1 mul_22_8_g922(.A0 (mul_22_8_n_69), .A1 (mul_22_8_n_82), .B0
       (mul_22_8_n_70), .Y (mul_22_8_n_88));
  XNOR2X1 mul_22_8_g923(.A (mul_22_8_n_78), .B (mul_22_8_n_82), .Y
       (out1[6]));
  NAND2XL mul_22_8_g924(.A (mul_22_8_n_84), .B (mul_22_8_n_76), .Y
       (mul_22_8_n_86));
  XNOR2X1 mul_22_8_g925(.A (mul_22_8_n_72), .B (mul_22_8_n_77), .Y
       (out1[5]));
  NOR2XL mul_22_8_g926(.A (mul_22_8_n_79), .B (mul_22_8_n_69), .Y
       (mul_22_8_n_84));
  OR2XL mul_22_8_g927(.A (mul_22_8_n_80), .B (mul_22_8_n_79), .Y
       (mul_22_8_n_83));
  NOR2X1 mul_22_8_g928(.A (mul_22_8_n_81), .B (mul_22_8_n_76), .Y
       (mul_22_8_n_82));
  NOR2X1 mul_22_8_g929(.A (mul_22_8_n_64), .B (mul_22_8_n_71), .Y
       (mul_22_8_n_81));
  AND2X1 mul_22_8_g930(.A (mul_22_8_n_65), .B (mul_22_8_n_74), .Y
       (mul_22_8_n_80));
  NOR2X1 mul_22_8_g931(.A (mul_22_8_n_65), .B (mul_22_8_n_74), .Y
       (mul_22_8_n_79));
  NOR2BX1 mul_22_8_g932(.AN (mul_22_8_n_70), .B (mul_22_8_n_69), .Y
       (mul_22_8_n_78));
  NAND2XL mul_22_8_g933(.A (mul_22_8_n_58), .B (mul_22_8_n_71), .Y
       (mul_22_8_n_77));
  OAI21X1 mul_22_8_g934(.A0 (mul_22_8_n_58), .A1 (mul_22_8_n_64), .B0
       (mul_22_8_n_63), .Y (mul_22_8_n_76));
  XNOR2X1 mul_22_8_g935(.A (mul_22_8_n_68), .B (mul_22_8_n_62), .Y
       (out1[4]));
  ADDFX1 mul_22_8_g936(.A (mul_22_8_n_41), .B (mul_22_8_n_50), .CI
       (mul_22_8_n_23), .CO (mul_22_8_n_73), .S (mul_22_8_n_74));
  NAND2BX1 mul_22_8_g937(.AN (mul_22_8_n_64), .B (mul_22_8_n_63), .Y
       (mul_22_8_n_72));
  NAND2BX1 mul_22_8_g938(.AN (mul_22_8_n_59), .B (mul_22_8_n_68), .Y
       (mul_22_8_n_71));
  NAND2X1 mul_22_8_g939(.A (mul_22_8_n_60), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_70));
  NOR2X1 mul_22_8_g940(.A (mul_22_8_n_60), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_69));
  ADDFX1 mul_22_8_g941(.A (mul_22_8_n_52), .B (mul_22_8_n_34), .CI
       (mul_22_8_n_48), .CO (mul_22_8_n_68), .S (out1[3]));
  ADDFX1 mul_22_8_g942(.A (mul_22_8_n_44), .B (mul_22_8_n_19), .CI
       (mul_22_8_n_51), .CO (mul_22_8_n_65), .S (mul_22_8_n_66));
  NOR2X1 mul_22_8_g943(.A (mul_22_8_n_54), .B (mul_22_8_n_61), .Y
       (mul_22_8_n_64));
  NAND2X1 mul_22_8_g944(.A (mul_22_8_n_54), .B (mul_22_8_n_61), .Y
       (mul_22_8_n_63));
  NAND2BX1 mul_22_8_g945(.AN (mul_22_8_n_59), .B (mul_22_8_n_58), .Y
       (mul_22_8_n_62));
  ADDFX1 mul_22_8_g946(.A (mul_22_8_n_42), .B (mul_22_8_n_1), .CI
       (mul_22_8_n_45), .CO (mul_22_8_n_60), .S (mul_22_8_n_61));
  NOR2X1 mul_22_8_g947(.A (mul_22_8_n_49), .B (mul_22_8_n_55), .Y
       (mul_22_8_n_59));
  NAND2X1 mul_22_8_g948(.A (mul_22_8_n_49), .B (mul_22_8_n_55), .Y
       (mul_22_8_n_58));
  ADDFX1 mul_22_8_g949(.A (mul_22_8_n_40), .B (mul_22_8_n_37), .CI
       (mul_22_8_n_22), .CO (mul_22_8_n_56), .S (mul_22_8_n_57));
  ADDFX1 mul_22_8_g950(.A (mul_22_8_n_43), .B (mul_22_8_n_33), .CI
       (mul_22_8_n_8), .CO (mul_22_8_n_54), .S (mul_22_8_n_55));
  ADDFX1 mul_22_8_g951(.A (mul_22_8_n_32), .B (mul_22_8_n_26), .CI
       (mul_22_8_n_39), .CO (mul_22_8_n_52), .S (out1[2]));
  ADDFX1 mul_22_8_g952(.A (mul_22_8_n_10), .B (mul_22_8_n_18), .CI
       (mul_22_8_n_4), .CO (mul_22_8_n_50), .S (mul_22_8_n_51));
  ADDFX1 mul_22_8_g953(.A (mul_22_8_n_38), .B (mul_22_8_n_7), .CI
       (mul_22_8_n_16), .CO (mul_22_8_n_49), .S (mul_22_8_n_48));
  ADDFX1 mul_22_8_g954(.A (mul_22_8_n_36), .B (mul_22_8_n_6), .CI
       (mul_22_8_n_5), .CO (mul_22_8_n_46), .S (mul_22_8_n_47));
  ADDFX1 mul_22_8_g955(.A (mul_22_8_n_14), .B (mul_22_8_n_0), .CI
       (mul_22_8_n_17), .CO (mul_22_8_n_44), .S (mul_22_8_n_45));
  ADDFX1 mul_22_8_g956(.A (mul_22_8_n_11), .B (mul_22_8_n_3), .CI
       (mul_22_8_n_20), .CO (mul_22_8_n_42), .S (mul_22_8_n_43));
  ADDFX1 mul_22_8_g957(.A (mul_22_8_n_24), .B (mul_22_8_n_2), .CI
       (mul_22_8_n_21), .CO (mul_22_8_n_40), .S (mul_22_8_n_41));
  ADDHX1 mul_22_8_g958(.A (mul_22_8_n_25), .B (mul_22_8_n_13), .CO
       (mul_22_8_n_38), .S (mul_22_8_n_39));
  ADDHX1 mul_22_8_g959(.A (mul_22_8_n_12), .B (mul_22_8_n_9), .CO
       (mul_22_8_n_36), .S (mul_22_8_n_37));
  AOI21X1 mul_22_8_g960(.A0 (mul_22_8_n_30), .A1 (mul_22_8_n_31), .B0
       (mul_22_8_n_32), .Y (out1[1]));
  OAI2BB1X1 mul_22_8_g961(.A0N (mul_22_8_n_28), .A1N (mul_22_8_n_29),
       .B0 (mul_22_8_n_33), .Y (mul_22_8_n_34));
  OR2X1 mul_22_8_g962(.A (mul_22_8_n_29), .B (mul_22_8_n_28), .Y
       (mul_22_8_n_33));
  NOR2X1 mul_22_8_g963(.A (mul_22_8_n_30), .B (mul_22_8_n_31), .Y
       (mul_22_8_n_32));
  AND2XL mul_22_8_g964(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g965(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_31));
  AND2XL mul_22_8_g966(.A (in2[0]), .B (in1[2]), .Y (mul_22_8_n_26));
  NAND2X1 mul_22_8_g967(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_30));
  AND2XL mul_22_8_g968(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_29));
  NAND2X1 mul_22_8_g969(.A (in2[0]), .B (in1[3]), .Y (mul_22_8_n_28));
  AND2XL mul_22_8_g970(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_25));
  AND2XL mul_22_8_g971(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_24));
  NAND2X1 mul_22_8_g972(.A (in2[4]), .B (in1[3]), .Y (mul_22_8_n_23));
  AND2XL mul_22_8_g973(.A (in2[6]), .B (in1[2]), .Y (mul_22_8_n_22));
  AND2XL mul_22_8_g974(.A (in2[5]), .B (in1[2]), .Y (mul_22_8_n_21));
  AND2XL mul_22_8_g975(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_20));
  NAND2X1 mul_22_8_g976(.A (in2[3]), .B (in1[3]), .Y (mul_22_8_n_19));
  AND2XL mul_22_8_g977(.A (in2[6]), .B (in1[0]), .Y (mul_22_8_n_18));
  AND2XL mul_22_8_g978(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_17));
  AND2XL mul_22_8_g979(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_16));
  NAND2X1 mul_22_8_g980(.A (in2[7]), .B (in1[3]), .Y (mul_22_8_n_15));
  AND2XL mul_22_8_g981(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_14));
  AND2XL mul_22_8_g982(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_13));
  NAND2X1 mul_22_8_g983(.A (in2[5]), .B (in1[3]), .Y (mul_22_8_n_12));
  AND2XL mul_22_8_g984(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_11));
  AND2XL mul_22_8_g985(.A (in2[4]), .B (in1[2]), .Y (mul_22_8_n_10));
  AND2XL mul_22_8_g986(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_9));
  NAND2X1 mul_22_8_g987(.A (in2[1]), .B (in1[3]), .Y (mul_22_8_n_8));
  AND2XL mul_22_8_g988(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_7));
  NAND2X1 mul_22_8_g989(.A (in2[6]), .B (in1[3]), .Y (mul_22_8_n_6));
  AND2XL mul_22_8_g990(.A (in2[7]), .B (in1[2]), .Y (mul_22_8_n_5));
  AND2XL mul_22_8_g991(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_4));
  AND2XL mul_22_8_g992(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_3));
  AND2XL mul_22_8_g993(.A (in2[7]), .B (in1[0]), .Y (mul_22_8_n_2));
  NAND2X1 mul_22_8_g994(.A (in2[2]), .B (in1[3]), .Y (mul_22_8_n_1));
  AND2XL mul_22_8_g995(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_0));
endmodule


