`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:46:16 CST (Apr 12 2022 06:46:16 UTC)

module GaussFilter_N_Mux_2_2_2_4(ctrl1, out1);
  input ctrl1;
  output [1:0] out1;
  wire ctrl1;
  wire [1:0] out1;
  assign out1[0] = ctrl1;
  assign out1[1] = ctrl1;
endmodule


