`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:19 CST (Apr 12 2022 13:35:19 UTC)

module GaussFilter_Mul_8Ux4S_12S_1(in2, in1, out1);
  input [7:0] in2;
  input [3:0] in1;
  output [11:0] out1;
  wire [7:0] in2;
  wire [3:0] in1;
  wire [11:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_10;
  wire mul_22_8_n_11, mul_22_8_n_12, mul_22_8_n_13, mul_22_8_n_19,
       mul_22_8_n_20, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24;
  wire mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27, mul_22_8_n_28,
       mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32;
  wire mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36,
       mul_22_8_n_37, mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40;
  wire mul_22_8_n_41, mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44,
       mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49;
  wire mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_53,
       mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_58;
  wire mul_22_8_n_60, mul_22_8_n_62, mul_22_8_n_63, mul_22_8_n_64,
       mul_22_8_n_65, mul_22_8_n_66, mul_22_8_n_68, mul_22_8_n_69;
  wire mul_22_8_n_70, mul_22_8_n_71, mul_22_8_n_72, mul_22_8_n_73,
       mul_22_8_n_74, mul_22_8_n_75, mul_22_8_n_76, mul_22_8_n_77;
  wire mul_22_8_n_78, mul_22_8_n_79, mul_22_8_n_80, mul_22_8_n_81,
       mul_22_8_n_82, mul_22_8_n_83, mul_22_8_n_84, mul_22_8_n_85;
  wire mul_22_8_n_86, mul_22_8_n_87, mul_22_8_n_88, mul_22_8_n_89,
       mul_22_8_n_91, mul_22_8_n_92, mul_22_8_n_93, mul_22_8_n_94;
  wire mul_22_8_n_95, mul_22_8_n_96, mul_22_8_n_97, mul_22_8_n_98,
       mul_22_8_n_99, mul_22_8_n_101, mul_22_8_n_102, mul_22_8_n_103;
  wire mul_22_8_n_104, mul_22_8_n_105, mul_22_8_n_106, mul_22_8_n_108,
       mul_22_8_n_109, mul_22_8_n_110, mul_22_8_n_111, mul_22_8_n_112;
  wire mul_22_8_n_113, mul_22_8_n_114, mul_22_8_n_115, mul_22_8_n_117,
       mul_22_8_n_118, mul_22_8_n_119, mul_22_8_n_120, mul_22_8_n_121;
  wire mul_22_8_n_122, mul_22_8_n_123, mul_22_8_n_124, mul_22_8_n_125,
       mul_22_8_n_126, mul_22_8_n_127, mul_22_8_n_128, mul_22_8_n_129;
  wire mul_22_8_n_131, mul_22_8_n_133, mul_22_8_n_134, mul_22_8_n_136,
       mul_22_8_n_139, mul_22_8_n_140, mul_22_8_n_156, mul_22_8_n_157;
  wire mul_22_8_n_158, mul_22_8_n_159, mul_22_8_n_160, mul_22_8_n_162,
       mul_22_8_n_163, mul_22_8_n_164, mul_22_8_n_165, mul_22_8_n_166;
  wire mul_22_8_n_168, mul_22_8_n_169, mul_22_8_n_171, mul_22_8_n_172,
       mul_22_8_n_173, mul_22_8_n_174, mul_22_8_n_176, mul_22_8_n_178;
  wire mul_22_8_n_179, mul_22_8_n_187, mul_22_8_n_188, mul_22_8_n_189,
       mul_22_8_n_192, mul_22_8_n_193, mul_22_8_n_194, mul_22_8_n_196;
  wire mul_22_8_n_197, mul_22_8_n_205, mul_22_8_n_206, mul_22_8_n_207,
       mul_22_8_n_209, mul_22_8_n_211, mul_22_8_n_212, mul_22_8_n_213;
  wire mul_22_8_n_214, mul_22_8_n_215, mul_22_8_n_216, mul_22_8_n_217,
       mul_22_8_n_218, mul_22_8_n_219, mul_22_8_n_227, mul_22_8_n_228;
  wire mul_22_8_n_229;
  NOR2BX1 mul_22_8_g963(.AN (mul_22_8_n_84), .B (mul_22_8_n_140), .Y
       (out1[11]));
  MXI2X1 mul_22_8_g964(.A (mul_22_8_n_87), .B (mul_22_8_n_88), .S0
       (mul_22_8_n_13), .Y (out1[10]));
  NOR2X1 mul_22_8_g966(.A (mul_22_8_n_83), .B (mul_22_8_n_13), .Y
       (mul_22_8_n_140));
  AOI21X2 mul_22_8_g969(.A0 (mul_22_8_n_112), .A1 (mul_22_8_n_227), .B0
       (mul_22_8_n_108), .Y (mul_22_8_n_139));
  MXI2XL mul_22_8_g970(.A (mul_22_8_n_124), .B (mul_22_8_n_125), .S0
       (mul_22_8_n_228), .Y (out1[8]));
  MXI2XL mul_22_8_g971(.A (mul_22_8_n_123), .B (mul_22_8_n_122), .S0
       (mul_22_8_n_136), .Y (out1[7]));
  AOI21X1 mul_22_8_g972(.A0 (mul_22_8_n_205), .A1 (mul_22_8_n_158), .B0
       (mul_22_8_n_218), .Y (mul_22_8_n_136));
  NOR2X2 mul_22_8_g975(.A (mul_22_8_n_129), .B (mul_22_8_n_133), .Y
       (mul_22_8_n_134));
  NOR2X2 mul_22_8_g976(.A (mul_22_8_n_127), .B (mul_22_8_n_131), .Y
       (mul_22_8_n_133));
  AOI21X2 mul_22_8_g978(.A0 (mul_22_8_n_110), .A1 (mul_22_8_n_118), .B0
       (mul_22_8_n_113), .Y (mul_22_8_n_131));
  MXI2XL mul_22_8_g979(.A (mul_22_8_n_119), .B (mul_22_8_n_120), .S0
       (mul_22_8_n_117), .Y (out1[5]));
  OAI21X1 mul_22_8_g980(.A0 (mul_22_8_n_106), .A1 (mul_22_8_n_115), .B0
       (mul_22_8_n_111), .Y (mul_22_8_n_129));
  OAI2BB1X1 mul_22_8_g981(.A0N (mul_22_8_n_95), .A1N (mul_22_8_n_108),
       .B0 (mul_22_8_n_96), .Y (mul_22_8_n_128));
  NAND2X2 mul_22_8_g982(.A (mul_22_8_n_114), .B (mul_22_8_n_211), .Y
       (mul_22_8_n_127));
  AND2XL mul_22_8_g983(.A (mul_22_8_n_95), .B (mul_22_8_n_112), .Y
       (mul_22_8_n_126));
  INVX1 mul_22_8_g984(.A (mul_22_8_n_124), .Y (mul_22_8_n_125));
  NOR2BX1 mul_22_8_g985(.AN (mul_22_8_n_112), .B (mul_22_8_n_108), .Y
       (mul_22_8_n_124));
  INVX1 mul_22_8_g986(.A (mul_22_8_n_122), .Y (mul_22_8_n_123));
  NAND2X1 mul_22_8_g987(.A (mul_22_8_n_111), .B (mul_22_8_n_209), .Y
       (mul_22_8_n_122));
  NAND2X1 mul_22_8_g989(.A (mul_22_8_n_219), .B (mul_22_8_n_206), .Y
       (mul_22_8_n_121));
  INVX1 mul_22_8_g990(.A (mul_22_8_n_119), .Y (mul_22_8_n_120));
  NOR2BX1 mul_22_8_g991(.AN (mul_22_8_n_110), .B (mul_22_8_n_113), .Y
       (mul_22_8_n_119));
  NAND2X2 mul_22_8_g992(.A (mul_22_8_n_6), .B (mul_22_8_n_109), .Y
       (mul_22_8_n_118));
  AOI21X1 mul_22_8_g993(.A0 (mul_22_8_n_5), .A1 (mul_22_8_n_193), .B0
       (mul_22_8_n_97), .Y (mul_22_8_n_117));
  NOR2X2 mul_22_8_g996(.A (mul_22_8_n_102), .B (mul_22_8_n_105), .Y
       (mul_22_8_n_115));
  OR2X1 mul_22_8_g997(.A (mul_22_8_n_94), .B (mul_22_8_n_103), .Y
       (mul_22_8_n_114));
  NOR2X1 mul_22_8_g998(.A (mul_22_8_n_86), .B (mul_22_8_n_93), .Y
       (mul_22_8_n_113));
  OR2XL mul_22_8_g999(.A (mul_22_8_n_104), .B (mul_22_8_n_92), .Y
       (mul_22_8_n_112));
  NAND2X1 mul_22_8_g1000(.A (mul_22_8_n_102), .B (mul_22_8_n_105), .Y
       (mul_22_8_n_111));
  NAND2X2 mul_22_8_g1001(.A (mul_22_8_n_86), .B (mul_22_8_n_93), .Y
       (mul_22_8_n_110));
  NAND2X2 mul_22_8_g1002(.A (mul_22_8_n_5), .B (mul_22_8_n_101), .Y
       (mul_22_8_n_109));
  AND2X1 mul_22_8_g1003(.A (mul_22_8_n_104), .B (mul_22_8_n_92), .Y
       (mul_22_8_n_108));
  NAND2X1 mul_22_8_g1005(.A (mul_22_8_n_94), .B (mul_22_8_n_103), .Y
       (mul_22_8_n_106));
  ADDFHXL mul_22_8_g1006(.A (mul_22_8_n_23), .B (mul_22_8_n_73), .CI
       (mul_22_8_n_72), .CO (mul_22_8_n_104), .S (mul_22_8_n_105));
  ADDFHXL mul_22_8_g1007(.A (mul_22_8_n_24), .B (mul_22_8_n_63), .CI
       (mul_22_8_n_74), .CO (mul_22_8_n_102), .S (mul_22_8_n_103));
  ADDFHX1 mul_22_8_g1009(.A (mul_22_8_n_60), .B (mul_22_8_n_81), .CI
       (mul_22_8_n_89), .CO (mul_22_8_n_101), .S (out1[3]));
  NOR2BX1 mul_22_8_g1010(.AN (mul_22_8_n_5), .B (mul_22_8_n_97), .Y
       (mul_22_8_n_99));
  NAND2X1 mul_22_8_g1012(.A (mul_22_8_n_96), .B (mul_22_8_n_95), .Y
       (mul_22_8_n_98));
  INVX1 mul_22_8_g1013(.A (mul_22_8_n_6), .Y (mul_22_8_n_97));
  NAND2X1 mul_22_8_g1016(.A (mul_22_8_n_80), .B (mul_22_8_n_91), .Y
       (mul_22_8_n_96));
  OR2XL mul_22_8_g1017(.A (mul_22_8_n_80), .B (mul_22_8_n_91), .Y
       (mul_22_8_n_95));
  OAI21X1 mul_22_8_g1018(.A0 (mul_22_8_n_78), .A1 (mul_22_8_n_157), .B0
       (mul_22_8_n_77), .Y (mul_22_8_n_94));
  XNOR2X1 mul_22_8_g1019(.A (mul_22_8_n_157), .B (mul_22_8_n_2), .Y
       (mul_22_8_n_93));
  ADDFX1 mul_22_8_g1020(.A (mul_22_8_n_71), .B (mul_22_8_n_65), .CI
       (mul_22_8_n_39), .CO (mul_22_8_n_91), .S (mul_22_8_n_92));
  ADDFX1 mul_22_8_g1022(.A (mul_22_8_n_53), .B (mul_22_8_n_0), .CI
       (mul_22_8_n_58), .CO (mul_22_8_n_89), .S (out1[2]));
  INVX1 mul_22_8_g1023(.A (mul_22_8_n_87), .Y (mul_22_8_n_88));
  NOR2BX1 mul_22_8_g1024(.AN (mul_22_8_n_84), .B (mul_22_8_n_83), .Y
       (mul_22_8_n_87));
  NOR2X1 mul_22_8_g1025(.A (mul_22_8_n_68), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_86));
  CLKXOR2X1 mul_22_8_g1026(.A (mul_22_8_n_70), .B (mul_22_8_n_76), .Y
       (mul_22_8_n_85));
  NAND2XL mul_22_8_g1027(.A (mul_22_8_n_37), .B (mul_22_8_n_79), .Y
       (mul_22_8_n_84));
  NOR2X1 mul_22_8_g1028(.A (mul_22_8_n_37), .B (mul_22_8_n_79), .Y
       (mul_22_8_n_83));
  ADDFHXL mul_22_8_g1032(.A (mul_22_8_n_54), .B (mul_22_8_n_11), .CI
       (mul_22_8_n_10), .CO (mul_22_8_n_82), .S (mul_22_8_n_81));
  ADDFX1 mul_22_8_g1033(.A (mul_22_8_n_64), .B (mul_22_8_n_42), .CI
       (mul_22_8_n_40), .CO (mul_22_8_n_79), .S (mul_22_8_n_80));
  NOR2X1 mul_22_8_g1034(.A (mul_22_8_n_33), .B (mul_22_8_n_75), .Y
       (mul_22_8_n_78));
  NAND2X1 mul_22_8_g1035(.A (mul_22_8_n_33), .B (mul_22_8_n_75), .Y
       (mul_22_8_n_77));
  ADDFHXL mul_22_8_g1037(.A (mul_22_8_n_26), .B (mul_22_8_n_41), .CI
       (mul_22_8_n_12), .CO (mul_22_8_n_75), .S (mul_22_8_n_76));
  ADDFHXL mul_22_8_g1038(.A (mul_22_8_n_27), .B (mul_22_8_n_38), .CI
       (mul_22_8_n_22), .CO (mul_22_8_n_73), .S (mul_22_8_n_74));
  ADDFHXL mul_22_8_g1039(.A (mul_22_8_n_44), .B (mul_22_8_n_43), .CI
       (mul_22_8_n_25), .CO (mul_22_8_n_71), .S (mul_22_8_n_72));
  MXI2XL mul_22_8_g1040(.A (mul_22_8_n_46), .B (mul_22_8_n_47), .S0
       (mul_22_8_n_55), .Y (mul_22_8_n_70));
  NOR2X1 mul_22_8_g1041(.A (mul_22_8_n_47), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_69));
  NOR2X1 mul_22_8_g1042(.A (mul_22_8_n_46), .B (mul_22_8_n_55), .Y
       (mul_22_8_n_68));
  INVX1 mul_22_8_g1044(.A (mul_22_8_n_55), .Y (mul_22_8_n_66));
  ADDHX1 mul_22_8_g1045(.A (mul_22_8_n_29), .B (mul_22_8_n_28), .CO
       (mul_22_8_n_64), .S (mul_22_8_n_65));
  NAND2X1 mul_22_8_g1046(.A (mul_22_8_n_1), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_63));
  NAND2X1 mul_22_8_g1047(.A (mul_22_8_n_34), .B (mul_22_8_n_56), .Y
       (mul_22_8_n_62));
  AOI21X1 mul_22_8_g1048(.A0 (mul_22_8_n_52), .A1 (mul_22_8_n_36), .B0
       (mul_22_8_n_53), .Y (out1[1]));
  NAND2BX1 mul_22_8_g1049(.AN (mul_22_8_n_3), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_60));
  MXI2XL mul_22_8_g1051(.A (mul_22_8_n_49), .B (mul_22_8_n_48), .S0
       (mul_22_8_n_50), .Y (mul_22_8_n_58));
  NAND2X1 mul_22_8_g1054(.A (mul_22_8_n_32), .B (mul_22_8_n_30), .Y
       (mul_22_8_n_56));
  NOR2X1 mul_22_8_g1056(.A (mul_22_8_n_35), .B (mul_22_8_n_51), .Y
       (mul_22_8_n_55));
  NOR2X4 mul_22_8_g1057(.A (mul_22_8_n_48), .B (mul_22_8_n_50), .Y
       (mul_22_8_n_54));
  NOR2X2 mul_22_8_g1059(.A (mul_22_8_n_52), .B (mul_22_8_n_36), .Y
       (mul_22_8_n_53));
  CLKINVX2 mul_22_8_g1061(.A (mul_22_8_n_48), .Y (mul_22_8_n_49));
  INVX1 mul_22_8_g1064(.A (mul_22_8_n_47), .Y (mul_22_8_n_46));
  AND2XL mul_22_8_g1066(.A (in2[0]), .B (mul_22_8_n_187), .Y (out1[0]));
  NAND2X1 mul_22_8_g1067(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_52));
  NAND2X1 mul_22_8_g1068(.A (in2[0]), .B (in1[3]), .Y (mul_22_8_n_51));
  NOR2X4 mul_22_8_g1069(.A (mul_22_8_n_166), .B (mul_22_8_n_173), .Y
       (mul_22_8_n_44));
  NAND2X4 mul_22_8_g1070(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_50));
  NAND2X8 mul_22_8_g1071(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_48));
  NOR2X4 mul_22_8_g1072(.A (mul_22_8_n_217), .B (mul_22_8_n_189), .Y
       (mul_22_8_n_43));
  NAND2X1 mul_22_8_g1073(.A (mul_22_8_n_164), .B (in1[3]), .Y
       (mul_22_8_n_42));
  NOR2X2 mul_22_8_g1074(.A (mul_22_8_n_20), .B (mul_22_8_n_179), .Y
       (mul_22_8_n_41));
  AND2XL mul_22_8_g1076(.A (mul_22_8_n_213), .B (in1[2]), .Y
       (mul_22_8_n_40));
  AND2XL mul_22_8_g1077(.A (mul_22_8_n_163), .B (in1[2]), .Y
       (mul_22_8_n_39));
  NAND2X1 mul_22_8_g1079(.A (in2[1]), .B (in1[3]), .Y (mul_22_8_n_47));
  NOR2X4 mul_22_8_g1081(.A (mul_22_8_n_162), .B (mul_22_8_n_189), .Y
       (mul_22_8_n_38));
  INVX1 mul_22_8_g1084(.A (mul_22_8_n_32), .Y (mul_22_8_n_31));
  NAND2X1 mul_22_8_g1086(.A (mul_22_8_n_212), .B (in1[3]), .Y
       (mul_22_8_n_37));
  NAND2X1 mul_22_8_g1087(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_36));
  NOR2X1 mul_22_8_g1088(.A (mul_22_8_n_20), .B (mul_22_8_n_188), .Y
       (mul_22_8_n_35));
  NAND2X1 mul_22_8_g1090(.A (in2[5]), .B (in1[3]), .Y (mul_22_8_n_29));
  NOR2X1 mul_22_8_g1091(.A (mul_22_8_n_215), .B (mul_22_8_n_176), .Y
       (mul_22_8_n_28));
  NOR2X4 mul_22_8_g1092(.A (mul_22_8_n_197), .B (mul_22_8_n_174), .Y
       (mul_22_8_n_27));
  NOR2X1 mul_22_8_g1093(.A (mul_22_8_n_168), .B (mul_22_8_n_178), .Y
       (mul_22_8_n_34));
  NOR2X4 mul_22_8_g1094(.A (mul_22_8_n_169), .B (mul_22_8_n_189), .Y
       (mul_22_8_n_26));
  NOR2X1 mul_22_8_g1095(.A (mul_22_8_n_19), .B (mul_22_8_n_196), .Y
       (mul_22_8_n_25));
  NAND2X1 mul_22_8_g1096(.A (in2[3]), .B (in1[3]), .Y (mul_22_8_n_24));
  NAND2X1 mul_22_8_g1097(.A (in2[2]), .B (in1[3]), .Y (mul_22_8_n_33));
  NAND2X1 mul_22_8_g1098(.A (in2[3]), .B (in1[2]), .Y (mul_22_8_n_32));
  NAND2X1 mul_22_8_g1099(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_30));
  NAND2X1 mul_22_8_g1100(.A (mul_22_8_n_171), .B (in1[3]), .Y
       (mul_22_8_n_23));
  NOR2X1 mul_22_8_g1101(.A (mul_22_8_n_172), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_22));
  CLKINVX3 mul_22_8_g1104(.A (in2[3]), .Y (mul_22_8_n_20));
  CLKINVX3 mul_22_8_g1105(.A (in1[2]), .Y (mul_22_8_n_19));
  AOI21X2 mul_22_8_g1111(.A0 (mul_22_8_n_126), .A1 (mul_22_8_n_229),
       .B0 (mul_22_8_n_128), .Y (mul_22_8_n_13));
  CLKAND2X3 mul_22_8_g2(.A (in2[2]), .B (in1[2]), .Y (mul_22_8_n_12));
  CLKAND2X2 mul_22_8_g1112(.A (in2[2]), .B (in1[1]), .Y
       (mul_22_8_n_11));
  AND2X1 mul_22_8_g1113(.A (in2[1]), .B (in1[2]), .Y (mul_22_8_n_10));
  CLKXOR2X1 mul_22_8_g1114(.A (mul_22_8_n_121), .B (mul_22_8_n_159), .Y
       (out1[6]));
  CLKXOR2X1 mul_22_8_g1115(.A (mul_22_8_n_192), .B (mul_22_8_n_99), .Y
       (out1[4]));
  CLKXOR2X1 mul_22_8_g1116(.A (mul_22_8_n_98), .B (mul_22_8_n_139), .Y
       (out1[9]));
  NAND2BX4 mul_22_8_g1117(.AN (mul_22_8_n_85), .B (mul_22_8_n_82), .Y
       (mul_22_8_n_6));
  NAND2BX2 mul_22_8_g1118(.AN (mul_22_8_n_82), .B (mul_22_8_n_85), .Y
       (mul_22_8_n_5));
  NOR2BX1 mul_22_8_g1119(.AN (mul_22_8_n_76), .B (mul_22_8_n_69), .Y
       (mul_22_8_n_4));
  AND2XL mul_22_8_g1120(.A (mul_22_8_n_51), .B (mul_22_8_n_35), .Y
       (mul_22_8_n_3));
  XNOR2X1 mul_22_8_g1121(.A (mul_22_8_n_33), .B (mul_22_8_n_75), .Y
       (mul_22_8_n_2));
  NAND2BX1 mul_22_8_g1122(.AN (mul_22_8_n_30), .B (mul_22_8_n_31), .Y
       (mul_22_8_n_1));
  NOR2BX1 mul_22_8_g1123(.AN (in2[0]), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_0));
  MXI2XL mul_22_8_g1124(.A (mul_22_8_n_32), .B (mul_22_8_n_31), .S0
       (mul_22_8_n_156), .Y (mul_22_8_n_157));
  XOR2XL mul_22_8_g3(.A (mul_22_8_n_30), .B (mul_22_8_n_34), .Y
       (mul_22_8_n_156));
  INVXL mul_22_8_fopt(.A (mul_22_8_n_160), .Y (mul_22_8_n_158));
  BUFX2 mul_22_8_fopt1125(.A (mul_22_8_n_160), .Y (mul_22_8_n_159));
  BUFX2 mul_22_8_fopt1126(.A (mul_22_8_n_131), .Y (mul_22_8_n_160));
  CLKINVX3 mul_22_8_fopt1127(.A (in2[6]), .Y (mul_22_8_n_162));
  INVXL mul_22_8_fopt1128(.A (mul_22_8_n_165), .Y (mul_22_8_n_163));
  INVXL mul_22_8_fopt1129(.A (mul_22_8_n_165), .Y (mul_22_8_n_164));
  INVXL mul_22_8_fopt1130(.A (in2[6]), .Y (mul_22_8_n_165));
  CLKINVX4 mul_22_8_fopt1131(.A (in2[6]), .Y (mul_22_8_n_166));
  INVXL mul_22_8_fopt1132(.A (in2[4]), .Y (mul_22_8_n_168));
  CLKINVX2 mul_22_8_fopt1133(.A (in2[4]), .Y (mul_22_8_n_169));
  INVXL mul_22_8_fopt1134(.A (mul_22_8_n_172), .Y (mul_22_8_n_171));
  CLKINVX3 mul_22_8_fopt1135(.A (in2[4]), .Y (mul_22_8_n_172));
  CLKINVX3 mul_22_8_fopt1136(.A (in1[1]), .Y (mul_22_8_n_173));
  CLKINVX3 mul_22_8_fopt1137(.A (in1[1]), .Y (mul_22_8_n_174));
  INVXL mul_22_8_fopt1138(.A (in1[1]), .Y (mul_22_8_n_176));
  INVXL mul_22_8_fopt1139(.A (in1[1]), .Y (mul_22_8_n_178));
  CLKINVX2 mul_22_8_fopt1140(.A (in1[1]), .Y (mul_22_8_n_179));
  INVXL mul_22_8_fopt1144(.A (mul_22_8_n_188), .Y (mul_22_8_n_187));
  CLKINVX1 mul_22_8_fopt1145(.A (in1[0]), .Y (mul_22_8_n_188));
  CLKINVX6 mul_22_8_fopt1146(.A (in1[0]), .Y (mul_22_8_n_189));
  INVXL mul_22_8_fopt1147(.A (mul_22_8_n_194), .Y (mul_22_8_n_192));
  INVXL mul_22_8_fopt1148(.A (mul_22_8_n_194), .Y (mul_22_8_n_193));
  INVXL mul_22_8_fopt1149(.A (mul_22_8_n_101), .Y (mul_22_8_n_194));
  CLKINVX1 mul_22_8_fopt1150(.A (in2[5]), .Y (mul_22_8_n_196));
  CLKINVX4 mul_22_8_fopt1151(.A (in2[5]), .Y (mul_22_8_n_197));
  INVXL mul_22_8_fopt1155(.A (mul_22_8_n_207), .Y (mul_22_8_n_205));
  INVXL mul_22_8_fopt1156(.A (mul_22_8_n_207), .Y (mul_22_8_n_206));
  INVXL mul_22_8_fopt1157(.A (mul_22_8_n_114), .Y (mul_22_8_n_207));
  INVXL mul_22_8_fopt1158(.A (mul_22_8_n_115), .Y (mul_22_8_n_209));
  CLKINVX2 mul_22_8_fopt1159(.A (mul_22_8_n_115), .Y (mul_22_8_n_211));
  INVXL mul_22_8_fopt1160(.A (mul_22_8_n_214), .Y (mul_22_8_n_212));
  INVXL mul_22_8_fopt1161(.A (mul_22_8_n_214), .Y (mul_22_8_n_213));
  INVXL mul_22_8_fopt1162(.A (mul_22_8_n_216), .Y (mul_22_8_n_214));
  INVXL mul_22_8_fopt1163(.A (mul_22_8_n_216), .Y (mul_22_8_n_215));
  INVXL mul_22_8_fopt1164(.A (mul_22_8_n_217), .Y (mul_22_8_n_216));
  CLKINVX4 mul_22_8_fopt1165(.A (in2[7]), .Y (mul_22_8_n_217));
  INVXL mul_22_8_fopt1166(.A (mul_22_8_n_219), .Y (mul_22_8_n_218));
  BUFX3 mul_22_8_fopt1167(.A (mul_22_8_n_106), .Y (mul_22_8_n_219));
  CLKINVX1 mul_22_8_fopt1173(.A (mul_22_8_n_134), .Y (mul_22_8_n_227));
  INVXL mul_22_8_fopt1174(.A (mul_22_8_n_229), .Y (mul_22_8_n_228));
  CLKINVX1 mul_22_8_fopt1175(.A (mul_22_8_n_134), .Y (mul_22_8_n_229));
endmodule


