`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:12 CST (Apr 12 2022 13:35:12 UTC)

module GaussFilter_N_Mux_4_3_0_4(ctrl1, out1);
  input [1:0] ctrl1;
  output [3:0] out1;
  wire [1:0] ctrl1;
  wire [3:0] out1;
  assign out1[3] = 1'b0;
  NOR2X1 g16(.A (out1[1]), .B (ctrl1[1]), .Y (out1[2]));
  NOR2BX1 g17(.AN (ctrl1[1]), .B (out1[1]), .Y (out1[0]));
  INVX1 g18(.A (ctrl1[0]), .Y (out1[1]));
endmodule


