`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 13 2022 07:20:27 CST (Apr 12 2022 23:20:27 UTC)

module GaussFilter_N_Mux_4_6_21_1(ctrl1, out1);
  input [3:0] ctrl1;
  output [3:0] out1;
  wire [3:0] ctrl1;
  wire [3:0] out1;
  wire n_0, n_1, n_2, n_4, n_5;
  assign out1[3] = 1'b0;
  OAI21X2 g24(.A0 (ctrl1[0]), .A1 (n_5), .B0 (n_2), .Y (out1[0]));
  NOR3X1 g25(.A (ctrl1[0]), .B (ctrl1[3]), .C (n_4), .Y (out1[2]));
  CLKINVX3 g27(.A (n_4), .Y (n_5));
  NOR2X1 g26(.A (n_0), .B (ctrl1[3]), .Y (out1[1]));
  NAND2X8 g28(.A (ctrl1[2]), .B (n_1), .Y (n_4));
  INVX1 g30(.A (ctrl1[3]), .Y (n_2));
  CLKINVX12 g31(.A (ctrl1[1]), .Y (n_1));
  INVX1 g29(.A (ctrl1[0]), .Y (n_0));
endmodule


