`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:46:15 CST (Apr 12 2022 06:46:15 UTC)

module GaussFilter_Mul_3Ux2U_5U_4(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_4,
       mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_8;
  ADDHX1 mul_22_8_g123(.A (mul_22_8_n_2), .B (mul_22_8_n_8), .CO
       (out1[4]), .S (out1[3]));
  ADDFX1 mul_22_8_g124(.A (mul_22_8_n_6), .B (mul_22_8_n_5), .CI
       (mul_22_8_n_0), .CO (mul_22_8_n_8), .S (out1[2]));
  AOI21X1 mul_22_8_g125(.A0 (mul_22_8_n_1), .A1 (mul_22_8_n_4), .B0
       (mul_22_8_n_6), .Y (out1[1]));
  NOR2X1 mul_22_8_g126(.A (mul_22_8_n_1), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_6));
  AND2XL mul_22_8_g127(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_5));
  NAND2X1 mul_22_8_g128(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_4));
  AND2XL mul_22_8_g129(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  AND2XL mul_22_8_g130(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_2));
  NAND2X1 mul_22_8_g131(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_1));
  AND2XL mul_22_8_g132(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_0));
endmodule


