`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 21:35:26 CST (Apr 12 2022 13:35:26 UTC)

module GaussFilter_NotEQ_2Ux1U_1U_1(in2, in1, out1);
  input [1:0] in2;
  input in1;
  output out1;
  wire [1:0] in2;
  wire in1;
  wire out1;
  wire n_0, n_1, n_2, n_3;
  NAND2X2 g17(.A (n_2), .B (n_3), .Y (out1));
  AOI21X4 g18(.A0 (in1), .A1 (n_0), .B0 (in2[1]), .Y (n_3));
  NAND2X2 g19(.A (in2[0]), .B (n_1), .Y (n_2));
  CLKINVX2 g20(.A (in1), .Y (n_1));
  CLKINVX12 g21(.A (in2[0]), .Y (n_0));
endmodule


