`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:51:48 CST (Apr 12 2022 06:51:48 UTC)

module GaussFilter_Mul2i3Add2u2u2_1(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire add_24_2_n_0, add_24_2_n_1, add_24_2_n_2, add_24_2_n_3,
       add_24_2_n_4, add_24_2_n_5, const_mul_27_11_n_0,
       const_mul_27_11_n_1;
  wire const_mul_27_11_n_2, const_mul_27_11_n_3, const_mul_27_11_n_4,
       const_mul_27_11_n_5, const_mul_27_11_n_7, const_mul_27_11_n_8,
       const_mul_27_11_n_10, const_mul_27_11_n_16;
  wire n_1, n_2;
  OAI21X1 add_24_2_g27(.A0 (add_24_2_n_3), .A1 (add_24_2_n_5), .B0
       (add_24_2_n_4), .Y (n_2));
  CLKXOR2X1 add_24_2_g28(.A (add_24_2_n_3), .B (add_24_2_n_2), .Y
       (n_1));
  NAND2X1 add_24_2_g30(.A (add_24_2_n_0), .B (add_24_2_n_1), .Y
       (out1[0]));
  NOR2X2 add_24_2_g33(.A (in2[1]), .B (in1[1]), .Y (add_24_2_n_5));
  NAND2X1 add_24_2_g35(.A (in2[1]), .B (in1[1]), .Y (add_24_2_n_4));
  NAND2X1 add_24_2_g36(.A (in2[0]), .B (in1[0]), .Y (add_24_2_n_3));
  NAND2BX1 add_24_2_g2(.AN (add_24_2_n_5), .B (add_24_2_n_4), .Y
       (add_24_2_n_2));
  NAND2BX1 add_24_2_g39(.AN (in1[0]), .B (in2[0]), .Y (add_24_2_n_1));
  NAND2BX1 add_24_2_g40(.AN (in2[0]), .B (in1[0]), .Y (add_24_2_n_0));
  MXI2X1 const_mul_27_11_g106(.A (const_mul_27_11_n_1), .B (n_2), .S0
       (const_mul_27_11_n_10), .Y (out1[3]));
  AOI21X1 const_mul_27_11_g107(.A0 (const_mul_27_11_n_5), .A1
       (const_mul_27_11_n_8), .B0 (const_mul_27_11_n_1), .Y (out1[4]));
  OAI21X1 const_mul_27_11_g108(.A0 (const_mul_27_11_n_2), .A1
       (const_mul_27_11_n_3), .B0 (const_mul_27_11_n_5), .Y
       (const_mul_27_11_n_10));
  MXI2X1 const_mul_27_11_g109(.A (const_mul_27_11_n_7), .B
       (const_mul_27_11_n_2), .S0 (const_mul_27_11_n_0), .Y (out1[2]));
  NAND2BX1 const_mul_27_11_g110(.AN (const_mul_27_11_n_3), .B
       (const_mul_27_11_n_7), .Y (const_mul_27_11_n_8));
  INVX2 const_mul_27_11_g111(.A (const_mul_27_11_n_2), .Y
       (const_mul_27_11_n_7));
  NOR2X1 const_mul_27_11_g113(.A (const_mul_27_11_n_7), .B
       (const_mul_27_11_n_4), .Y (out1[1]));
  NAND2X1 const_mul_27_11_g114(.A (n_2), .B (n_1), .Y
       (const_mul_27_11_n_5));
  NOR2X1 const_mul_27_11_g115(.A (const_mul_27_11_n_16), .B (out1[0]),
       .Y (const_mul_27_11_n_4));
  NOR2X1 const_mul_27_11_g117(.A (n_2), .B (n_1), .Y
       (const_mul_27_11_n_3));
  NAND2X2 const_mul_27_11_g119(.A (out1[0]), .B (n_1), .Y
       (const_mul_27_11_n_2));
  INVX1 const_mul_27_11_g120(.A (n_2), .Y (const_mul_27_11_n_1));
  NAND2BX1 const_mul_27_11_g2(.AN (const_mul_27_11_n_3), .B
       (const_mul_27_11_n_5), .Y (const_mul_27_11_n_0));
  BUFX2 const_mul_27_11_fopt(.A (n_1), .Y (const_mul_27_11_n_16));
endmodule


