`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 12 2022 14:51:00 CST (Apr 12 2022 06:51:00 UTC)

module GaussFilter_Mul2i3Add2u2u2_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire add_24_2_n_0, const_mul_27_11_n_0, const_mul_27_11_n_2, n_1, n_2;
  ADDHX1 const_mul_27_11_g55(.A (n_2), .B (const_mul_27_11_n_2), .CO
       (out1[4]), .S (out1[3]));
  ADDFX1 const_mul_27_11_g56(.A (const_mul_27_11_n_0), .B (n_1), .CI
       (n_2), .CO (const_mul_27_11_n_2), .S (out1[2]));
  ADDHX1 const_mul_27_11_g57(.A (n_1), .B (out1[0]), .CO
       (const_mul_27_11_n_0), .S (out1[1]));
  ADDFX1 add_24_2_g42(.A (add_24_2_n_0), .B (in1[1]), .CI (in2[1]), .CO
       (n_2), .S (n_1));
  ADDHX1 add_24_2_g43(.A (in2[0]), .B (in1[0]), .CO (add_24_2_n_0), .S
       (out1[0]));
endmodule


