// Generated by stratus_hls 19.12-s100  (91710.131054)
// Tue Apr 12 21:28:35 2022
// from ../GaussFilter.cpp
#include "GaussFilter_rtl.h"

struct GaussFilter;
GaussFilter::GaussFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_rgb_busy("o_rgb_busy")
    ,o_rgb_vld("o_rgb_vld")
    ,o_rgb_data("o_rgb_data")
    ,o_rgb_m_req_m_prev_trig_req("o_rgb_m_req_m_prev_trig_req")
    ,GaussFilter_Xor_1Ux1U_1U_1_1_out1("GaussFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_rgb_m_unacked_req("o_rgb_m_unacked_req")
    ,GaussFilter_Or_1Ux1U_1U_4_2_out1("GaussFilter_Or_1Ux1U_1U_4_2_out1")
    ,GaussFilter_And_1Ux1U_1U_4_40_out1("GaussFilter_And_1Ux1U_1U_4_40_out1")
    ,GaussFilter_And_1Ux1U_1U_4_6_out1("GaussFilter_And_1Ux1U_1U_4_6_out1")
    ,GaussFilter_Not_1U_1U_4_5_out1("GaussFilter_Not_1U_1U_4_5_out1")
    ,GaussFilter_And_1Ux1U_1U_4_7_out1("GaussFilter_And_1Ux1U_1U_4_7_out1")
    ,GaussFilter_N_Muxb_1_2_3_4_4_out1("GaussFilter_N_Muxb_1_2_3_4_4_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,GaussFilter_gen_busy_r_4_42_gnew_req("GaussFilter_gen_busy_r_4_42_gnew_req")
    ,GaussFilter_gen_busy_r_4_42_gen_busy_i_rgb_m_data_is_invalid_next("GaussFilter_gen_busy_r_4_42_gen_busy_i_rgb_m_data_is_invalid_next")
    ,GaussFilter_gen_busy_r_4_42_gdiv("GaussFilter_gen_busy_r_4_42_gdiv")
    ,GaussFilter_gen_busy_r_4_42_gnew_busy("GaussFilter_gen_busy_r_4_42_gnew_busy")
    ,i_rgb_m_data_is_valid("i_rgb_m_data_is_valid")
    ,GaussFilter_N_Mux_32_2_8_4_45_out1("GaussFilter_N_Mux_32_2_8_4_45_out1")
    ,stall_fifo_1_stall_fifo_1_0("stall_fifo_1_stall_fifo_1_0")
    ,active_0("active_0")
    ,GaussFilter_gen_fifo_addr_alt0_4_43_amtmp005("GaussFilter_gen_fifo_addr_alt0_4_43_amtmp005")
    ,GaussFilter_gen_fifo_addr_alt0_4_43_amtmp004("GaussFilter_gen_fifo_addr_alt0_4_43_amtmp004")
    ,GaussFilter_gen_fifo_addr_alt0_4_43_out1("GaussFilter_gen_fifo_addr_alt0_4_43_out1")
    ,fifo_dsel("fifo_dsel")
    ,global_state_next("global_state_next")
    ,r_busy("r_busy")
    ,gs_ctrl10("gs_ctrl10")
    ,GaussFilter_LessThan_29Sx9S_1U_4_25_out1("GaussFilter_LessThan_29Sx9S_1U_4_25_out1")
    ,GaussFilter_N_Mux_29_2_1_4_24_out1("GaussFilter_N_Mux_29_2_1_4_24_out1")
    ,GaussFilter_N_Mux_29_2_1_4_24_ctrl1("GaussFilter_N_Mux_29_2_1_4_24_ctrl1")
    ,GaussFilter_Add_28Sx1U_29S_4_23_out1("GaussFilter_Add_28Sx1U_29S_4_23_out1")
    ,GaussFilter_Add_28Sx1U_29S_4_23_in2("GaussFilter_Add_28Sx1U_29S_4_23_in2")
    ,GaussFilter_And_1Ux1U_1U_4_22_out1("GaussFilter_And_1Ux1U_1U_4_22_out1")
    ,GaussFilter_And_1Ux1U_1U_4_22_in1("GaussFilter_And_1Ux1U_1U_4_22_in1")
    ,GaussFilter_OrReduction_4U_1U_4_21_out1("GaussFilter_OrReduction_4U_1U_4_21_out1")
    ,GaussFilter_OrReduction_4U_1U_4_21_in1("GaussFilter_OrReduction_4U_1U_4_21_in1")
    ,gs_ctrl7("gs_ctrl7")
    ,GaussFilter_Add_32Ux32U_32U_4_15_in1("GaussFilter_Add_32Ux32U_32U_4_15_in1")
    ,GaussFilter_Mul_32Sx8U_32S_4_14_out1("GaussFilter_Mul_32Sx8U_32S_4_14_out1")
    ,GaussFilter_Mul_32Sx8U_32S_4_14_in1("GaussFilter_Mul_32Sx8U_32S_4_14_in1")
    ,GaussFilter_Mul_32Sx8U_32S_4_13_out1("GaussFilter_Mul_32Sx8U_32S_4_13_out1")
    ,GaussFilter_Mul_32Sx8U_32S_4_13_in1("GaussFilter_Mul_32Sx8U_32S_4_13_in1")
    ,GaussFilter_Mul_32Sx8U_32S_4_13_in2("GaussFilter_Mul_32Sx8U_32S_4_13_in2")
    ,i_rgb_m_stall_reg_full("i_rgb_m_stall_reg_full")
    ,i_rgb_m_stall_reg("i_rgb_m_stall_reg")
    ,GaussFilter_Add_2Ux1U_2U_4_11_in2("GaussFilter_Add_2Ux1U_2U_4_11_in2")
    ,GaussFilter_Add_4Ux2U_4U_4_10_out1("GaussFilter_Add_4Ux2U_4U_4_10_out1")
    ,GaussFilter_Add_4Ux2U_4U_4_10_in1("GaussFilter_Add_4Ux2U_4U_4_10_in1")
    ,GaussFilter_Mul_2Ux2U_4U_4_9_out1("GaussFilter_Mul_2Ux2U_4U_4_9_out1")
    ,GaussFilter_Mul_2Ux2U_4U_4_9_in2("GaussFilter_Mul_2Ux2U_4U_4_9_in2")
    ,GaussFilter_Add_2Ux1U_2U_4_8_in2("GaussFilter_Add_2Ux1U_2U_4_8_in2")
    ,gs_ctrl0("gs_ctrl0")
    ,GaussFilter_N_Mux_32_2_8_1_44_out1("GaussFilter_N_Mux_32_2_8_1_44_out1")
    ,s_reg_23("s_reg_23")
    ,GaussFilter_Add_2Ux1U_2U_4_11_out1("GaussFilter_Add_2Ux1U_2U_4_11_out1")
    ,s_reg_22("s_reg_22")
    ,s_reg_21("s_reg_21")
    ,GaussFilter_Add_32Ux32U_32U_4_16_out1("GaussFilter_Add_32Ux32U_32U_4_16_out1")
    ,s_reg_20("s_reg_20")
    ,GaussFilter_Add_32Ux32U_32U_4_15_out1("GaussFilter_Add_32Ux32U_32U_4_15_out1")
    ,s_reg_19("s_reg_19")
    ,GaussFilter_Add_2Ux1U_2U_4_8_out1("GaussFilter_Add_2Ux1U_2U_4_8_out1")
    ,s_reg_18("s_reg_18")
    ,s_reg_17("s_reg_17")
    ,GaussFilter_gen_busy_r_4_42_out1("GaussFilter_gen_busy_r_4_42_out1")
    ,GaussFilter_And_1Ux1U_1U_4_39_out1("GaussFilter_And_1Ux1U_1U_4_39_out1")
    ,GaussFilter_Not_1U_1U_1_3_out1("GaussFilter_Not_1U_1U_1_3_out1")
    ,o_rgb_m_req_m_trig_req("o_rgb_m_req_m_trig_req")
    ,GaussFilter_LessThan_2Ux2U_1U_4_20_out1("GaussFilter_LessThan_2Ux2U_1U_4_20_out1")
    ,GaussFilter_LessThan_2Ux2U_1U_4_19_out1("GaussFilter_LessThan_2Ux2U_1U_4_19_out1")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,GaussFilter_N_Mux_8_2_2_4_26_out1("GaussFilter_N_Mux_8_2_2_4_26_out1")
    ,s_reg_25("s_reg_25")
    ,s_reg_24("s_reg_24")
    ,GaussFilter_N_Mux_24_2_0_4_12_out1("GaussFilter_N_Mux_24_2_0_4_12_out1")
    ,global_state("global_state")
    ,stall0("stall0")
    ,mask_in1("mask_in1")
    ,mask_out1("mask_out1")
{
  mask = new GaussFilter_ROM_9X32_mask("mask");
  mask->in1(mask_in1);
  mask->out1(mask_out1);
  mask->clk(i_clk);

  SC_METHOD(drive_o_rgb_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_rgb_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( GaussFilter_gen_busy_r_4_42_out1 );
  sensitive << ( GaussFilter_And_1Ux1U_1U_4_39_out1 );

  SC_METHOD(drive_s_reg_17);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_18);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_19);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_20);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_21);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_22);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_23);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_24);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_25);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_GaussFilter_Add_2Ux1U_2U_4_8_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_18 );

  SC_METHOD(GaussFilter_Add_2Ux1U_2U_4_8);
  sensitive << ( GaussFilter_Add_2Ux1U_2U_4_8_in2 );

  SC_METHOD(drive_GaussFilter_Mul_2Ux2U_4U_4_9_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1 );
  sensitive << ( s_reg_22 );

  SC_METHOD(GaussFilter_Mul_2Ux2U_4U_4_9);
  sensitive << ( GaussFilter_Mul_2Ux2U_4U_4_9_in2 );

  SC_METHOD(drive_GaussFilter_Add_4Ux2U_4U_4_10_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1 );
  sensitive << ( s_reg_17 );
  sensitive << ( s_reg_18 );

  SC_METHOD(GaussFilter_Add_4Ux2U_4U_4_10);
  sensitive << ( GaussFilter_Add_4Ux2U_4U_4_10_in1 );
  sensitive << ( GaussFilter_Mul_2Ux2U_4U_4_9_out1 );

  SC_METHOD(drive_GaussFilter_Add_2Ux1U_2U_4_11_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1 );
  sensitive << ( s_reg_22 );

  SC_METHOD(GaussFilter_Add_2Ux1U_2U_4_11);
  sensitive << ( GaussFilter_Add_2Ux1U_2U_4_11_in2 );

  SC_METHOD(drive_mask_in1);
  sensitive << ( GaussFilter_Add_4Ux2U_4U_4_10_out1 );

  SC_METHOD(GaussFilter_N_Mux_24_2_0_4_12);
  sensitive << ( i_rgb_m_stall_reg_full );
  sensitive << ( i_rgb_m_stall_reg );
  sensitive << ( i_rgb_data );

  SC_METHOD(drive_GaussFilter_Mul_32Sx8U_32S_4_13_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_23 );
  sensitive << ( GaussFilter_N_Mux_32_2_8_1_44_out1 );

  SC_METHOD(drive_GaussFilter_Mul_32Sx8U_32S_4_13_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( o_rgb_data );
  sensitive << ( GaussFilter_N_Mux_24_2_0_4_12_out1 );

  SC_METHOD(GaussFilter_Mul_32Sx8U_32S_4_13);
  sensitive << ( GaussFilter_Mul_32Sx8U_32S_4_13_in1 );
  sensitive << ( GaussFilter_Mul_32Sx8U_32S_4_13_in2 );

  SC_METHOD(drive_GaussFilter_Mul_32Sx8U_32S_4_14_in1);
  sensitive << ( GaussFilter_N_Mux_24_2_0_4_12_out1 );

  SC_METHOD(GaussFilter_Mul_32Sx8U_32S_4_14);
  sensitive << ( GaussFilter_Mul_32Sx8U_32S_4_14_in1 );
  sensitive << ( GaussFilter_N_Mux_32_2_8_1_44_out1 );

  SC_METHOD(drive_GaussFilter_Add_32Ux32U_32U_4_15_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_21 );
  sensitive << ( s_reg_19 );

  SC_METHOD(GaussFilter_Add_32Ux32U_32U_4_15);
  sensitive << ( GaussFilter_Add_32Ux32U_32U_4_15_in1 );
  sensitive << ( GaussFilter_Mul_32Sx8U_32S_4_13_out1 );

  SC_METHOD(GaussFilter_Add_32Ux32U_32U_4_16);
  sensitive << ( s_reg_20 );
  sensitive << ( GaussFilter_Mul_32Sx8U_32S_4_14_out1 );

  SC_METHOD(GaussFilter_LessThan_2Ux2U_1U_4_19);
  sensitive << ( s_reg_22 );

  SC_METHOD(GaussFilter_LessThan_2Ux2U_1U_4_20);
  sensitive << ( s_reg_18 );

  SC_METHOD(drive_GaussFilter_OrReduction_4U_1U_4_21_in1);
  sensitive << ( gs_ctrl7 );
  sensitive << ( s_reg_20 );
  sensitive << ( s_reg_19 );

  SC_METHOD(GaussFilter_OrReduction_4U_1U_4_21);
  sensitive << ( GaussFilter_OrReduction_4U_1U_4_21_in1 );

  SC_METHOD(drive_GaussFilter_And_1Ux1U_1U_4_22_in1);
  sensitive << ( gs_ctrl7 );
  sensitive << ( s_reg_20 );
  sensitive << ( s_reg_19 );

  SC_METHOD(GaussFilter_And_1Ux1U_1U_4_22);
  sensitive << ( GaussFilter_And_1Ux1U_1U_4_22_in1 );
  sensitive << ( GaussFilter_OrReduction_4U_1U_4_21_out1 );

  SC_METHOD(drive_GaussFilter_Add_28Sx1U_29S_4_23_in2);
  sensitive << ( gs_ctrl7 );
  sensitive << ( s_reg_20 );
  sensitive << ( s_reg_19 );

  SC_METHOD(GaussFilter_Add_28Sx1U_29S_4_23);
  sensitive << ( GaussFilter_And_1Ux1U_1U_4_22_out1 );
  sensitive << ( GaussFilter_Add_28Sx1U_29S_4_23_in2 );

  SC_METHOD(drive_GaussFilter_N_Mux_29_2_1_4_24_ctrl1);
  sensitive << ( GaussFilter_Add_28Sx1U_29S_4_23_out1 );

  SC_METHOD(GaussFilter_N_Mux_29_2_1_4_24);
  sensitive << ( GaussFilter_N_Mux_29_2_1_4_24_ctrl1 );
  sensitive << ( GaussFilter_Add_28Sx1U_29S_4_23_out1 );

  SC_METHOD(GaussFilter_LessThan_29Sx9S_1U_4_25);
  sensitive << ( GaussFilter_N_Mux_29_2_1_4_24_out1 );

  SC_METHOD(GaussFilter_N_Mux_8_2_2_4_26);
  sensitive << ( GaussFilter_LessThan_29Sx9S_1U_4_25_out1 );
  sensitive << ( GaussFilter_N_Mux_29_2_1_4_24_out1 );

  SC_METHOD(drive_r_busy);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl10 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1 );
  sensitive << ( GaussFilter_LessThan_2Ux2U_1U_4_20_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl7);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl10);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_fifo_dsel);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_gen_fifo_addr_alt0_4_43_p4);
  sensitive << ( GaussFilter_gen_fifo_addr_alt0_4_43_amtmp005 );
  sensitive << ( fifo_dsel );
  sensitive << ( GaussFilter_gen_fifo_addr_alt0_4_43_amtmp004 );

  SC_METHOD(GaussFilter_gen_fifo_addr_alt0_4_43_p3);
  sensitive << ( fifo_dsel );
  sensitive << ( r_busy );
  sensitive << ( active_0 );

  SC_METHOD(GaussFilter_gen_fifo_addr_alt0_4_43_p2);
  sensitive << ( fifo_dsel );
  sensitive << ( r_busy );
  sensitive << ( active_0 );

  SC_METHOD(GaussFilter_N_Mux_32_2_8_1_44);
  sensitive << ( fifo_dsel );
  sensitive << ( stall_fifo_1_stall_fifo_1_0 );
  sensitive << ( mask_out1 );

  SC_METHOD(drive_stall_fifo_1_stall_fifo_1_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_N_Mux_32_2_8_4_45);
  sensitive << ( active_0 );
  sensitive << ( mask_out1 );
  sensitive << ( stall_fifo_1_stall_fifo_1_0 );

  SC_METHOD(drive_active_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( GaussFilter_gen_busy_r_4_42_out1 );

  SC_METHOD(drive_i_rgb_m_data_is_valid);
  sensitive << ( GaussFilter_gen_busy_r_4_42_out1 );

  SC_METHOD(GaussFilter_gen_busy_r_4_42_p10);
  sensitive << ( 
  GaussFilter_gen_busy_r_4_42_gen_busy_i_rgb_m_data_is_invalid_next );
  sensitive << ( GaussFilter_gen_busy_r_4_42_gdiv );
  sensitive << ( GaussFilter_gen_busy_r_4_42_gnew_busy );

  SC_METHOD(GaussFilter_gen_busy_r_4_42_p9);
  sensitive << ( GaussFilter_gen_busy_r_4_42_gdiv );

  SC_METHOD(GaussFilter_gen_busy_r_4_42_p8);
  sensitive << ( i_rgb_m_stall_reg_full );
  sensitive << ( GaussFilter_gen_busy_r_4_42_gnew_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(GaussFilter_gen_busy_r_4_42_p7);
  sensitive << ( i_rgb_m_stall_reg_full );
  sensitive << ( GaussFilter_gen_busy_r_4_42_gnew_req );

  SC_METHOD(GaussFilter_gen_busy_r_4_42_p6);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_m_busy_req_0 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_N_Muxb_1_2_3_4_4);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_i_rgb_m_stall_reg);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_Not_1U_1U_4_5);
  sensitive << ( i_rgb_m_stall_reg_full );

  SC_METHOD(GaussFilter_And_1Ux1U_1U_4_6);
  sensitive << ( stall0 );
  sensitive << ( i_rgb_m_data_is_valid );

  SC_METHOD(GaussFilter_And_1Ux1U_1U_4_7);
  sensitive << ( GaussFilter_Not_1U_1U_4_5_out1 );
  sensitive << ( GaussFilter_And_1Ux1U_1U_4_6_out1 );

  SC_METHOD(drive_i_rgb_m_stall_reg_full);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_And_1Ux1U_1U_4_40);
  sensitive << ( stall0 );
  sensitive << ( i_rgb_m_data_is_valid );

  SC_METHOD(drive_o_rgb_vld);
  sensitive << ( GaussFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(GaussFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( GaussFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_rgb_m_unacked_req );

  SC_METHOD(drive_o_rgb_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_And_1Ux1U_1U_4_39);
  sensitive << ( o_rgb_vld );
  sensitive << ( o_rgb_busy );

  SC_METHOD(GaussFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_rgb_m_req_m_prev_trig_req );
  sensitive << ( o_rgb_m_req_m_trig_req );

  SC_METHOD(drive_o_rgb_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussFilter_Not_1U_1U_1_3);
  sensitive << ( o_rgb_m_req_m_trig_req );

}
// resource: mux_24bx2i0c
// resource: regr_en_24
void GaussFilter::drive_o_rgb_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 1ULL: 
      o_rgb_data = GaussFilter_N_Mux_24_2_0_4_12_out1.read();
      break;
    case 4ULL: 
      o_rgb_data = ( (sc_uint<24> )(sc_bv<24>)((sc_bv<8>)(
                   GaussFilter_N_Mux_8_2_2_4_26_out1.read()), 
                   (sc_bv<16>)((sc_bv<8>)(s_reg_25.read()), 
                   (sc_bv<8>)(s_reg_24.read()))) );
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GaussFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 6ULL: 
        i_rgb_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 2ULL: 
        if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
          i_rgb_m_busy_req_0 = 0ULL;
        } else {
          if ( GaussFilter_LessThan_2Ux2U_1U_4_20_out1.read() ) {
            i_rgb_m_busy_req_0 = 0ULL;
          } 
        }
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void GaussFilter::drive_o_rgb_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_rgb_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 4ULL: 
        o_rgb_m_req_m_trig_req = (sc_uint<1> ) (GaussFilter_Not_1U_1U_1_3_out1
                                 .read());
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx3i1c
void GaussFilter::drive_stall0(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = (sc_uint<1> )GaussFilter_gen_busy_r_4_42_out1.read();
    break;
  case 5ULL: 
    stall0 = GaussFilter_And_1Ux1U_1U_4_39_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void GaussFilter::drive_s_reg_17(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_17 = 0ULL;
      break;
    case 2ULL: 
      if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() );
      else {
        s_reg_17 = s_reg_18.read();
      }
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GaussFilter::drive_s_reg_18(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_18 = (sc_uint<2> ) (GaussFilter_Add_2Ux1U_2U_4_8_out1.read());
      break;
    case 2ULL: 
      if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() );
      else {
        s_reg_18 = (sc_uint<2> ) (GaussFilter_Add_2Ux1U_2U_4_8_out1.read());
      }
      break;
    }
    break;
  }
}
// resource: mux_32bx2i1c
// resource: regr_en_32
void GaussFilter::drive_s_reg_19(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_19 = 0ULL;
      break;
    case 1ULL: 
      s_reg_19 = (sc_uint<32> ) (GaussFilter_Add_32Ux32U_32U_4_15_out1.read());
      break;
    case 2ULL: 
      if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() );
      else {
        if ( GaussFilter_LessThan_2Ux2U_1U_4_20_out1.read() );
        else {
          s_reg_19 = (sc_uint<32> ) (GaussFilter_Add_32Ux32U_32U_4_15_out1
                     .read());
        }
      }
      break;
    }
    break;
  }
}
// resource: mux_32bx2i1c
// resource: regr_en_32
void GaussFilter::drive_s_reg_20(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_20 = 0ULL;
      break;
    case 1ULL: 
      s_reg_20 = (sc_uint<32> ) (GaussFilter_Add_32Ux32U_32U_4_16_out1.read());
      break;
    }
    break;
  }
}
// resource: mux_32bx2i1c
// resource: regr_en_32
void GaussFilter::drive_s_reg_21(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_21 = 0ULL;
      break;
    case 2ULL: 
      s_reg_21 = (sc_uint<32> ) (GaussFilter_Add_32Ux32U_32U_4_15_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GaussFilter::drive_s_reg_22(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 2ULL: case 6ULL: 
      s_reg_22 = (sc_uint<2> ) (GaussFilter_Add_2Ux1U_2U_4_11_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_32
void GaussFilter::drive_s_reg_23(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    s_reg_23 = (sc_uint<32> ) (GaussFilter_N_Mux_32_2_8_1_44_out1.read());
    break;
  }
}
// resource: regr_en_8
void GaussFilter::drive_s_reg_24(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 2ULL: 
      s_reg_24 = GaussFilter_N_Mux_8_2_2_4_26_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void GaussFilter::drive_s_reg_25(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    s_reg_25 = GaussFilter_N_Mux_8_2_2_4_26_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
void GaussFilter::drive_GaussFilter_Add_2Ux1U_2U_4_8_in2(){
  if ( gs_ctrl0.read() ) {
    GaussFilter_Add_2Ux1U_2U_4_8_in2 = (sc_uint<2> ) (s_reg_18.read());
  } else {
    GaussFilter_Add_2Ux1U_2U_4_8_in2 = 0ULL;
  }
}
// resource: GaussFilter_Add_2Ux1U_2U_4  instance: GaussFilter_Add_2Ux1U_2U_4_8
void GaussFilter::GaussFilter_Add_2Ux1U_2U_4_8(){
  GaussFilter_Add_2Ux1U_2U_4_8_out1 = (/*cliff*/sc_uint<32>)(
                                      GaussFilter_Add_2Ux1U_2U_4_8_in2.read() + 
                                      1ULL);
}
// resource: mux_2bx2i1c
void GaussFilter::drive_GaussFilter_Mul_2Ux2U_4U_4_9_in2(){
  if ( gs_ctrl0.read() ) {
    if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
      GaussFilter_Mul_2Ux2U_4U_4_9_in2 = s_reg_22.read();
    } else {
      GaussFilter_Mul_2Ux2U_4U_4_9_in2 = 0ULL;
    }
  } else {
    GaussFilter_Mul_2Ux2U_4U_4_9_in2 = 0ULL;
  }
}
// resource: GaussFilter_Mul_2Ux2U_4U_4  instance: GaussFilter_Mul_2Ux2U_4U_4_9
void GaussFilter::GaussFilter_Mul_2Ux2U_4U_4_9(){
  GaussFilter_Mul_2Ux2U_4U_4_9_out1 = GaussFilter_Mul_2Ux2U_4U_4_9_in2.read() * 
                                      3ULL;
}
// resource: mux_2bx3i1c
void GaussFilter::drive_GaussFilter_Add_4Ux2U_4U_4_10_in1(){
  if ( gs_ctrl0.read() ) {
    if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
      GaussFilter_Add_4Ux2U_4U_4_10_in1 = s_reg_17.read();
    } else {
      GaussFilter_Add_4Ux2U_4U_4_10_in1 = s_reg_18.read();
    }
  } else {
    GaussFilter_Add_4Ux2U_4U_4_10_in1 = 0ULL;
  }
}
// resource: GaussFilter_Add_4Ux2U_4U_4  instance: GaussFilter_Add_4Ux2U_4U_4_10
void GaussFilter::GaussFilter_Add_4Ux2U_4U_4_10(){
  GaussFilter_Add_4Ux2U_4U_4_10_out1 = (GaussFilter_Mul_2Ux2U_4U_4_9_out1.read()
                                        + GaussFilter_Add_4Ux2U_4U_4_10_in1
                                       .read());
}
// resource: mux_2bx2i1c
void GaussFilter::drive_GaussFilter_Add_2Ux1U_2U_4_11_in2(){
  if ( gs_ctrl0.read() ) {
    if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
      GaussFilter_Add_2Ux1U_2U_4_11_in2 = (sc_uint<2> ) (s_reg_22.read());
    } else {
      GaussFilter_Add_2Ux1U_2U_4_11_in2 = 0ULL;
    }
  } else {
    GaussFilter_Add_2Ux1U_2U_4_11_in2 = 0ULL;
  }
}
// resource: GaussFilter_Add_2Ux1U_2U_4  instance: GaussFilter_Add_2Ux1U_2U_4_11
void GaussFilter::GaussFilter_Add_2Ux1U_2U_4_11(){
  GaussFilter_Add_2Ux1U_2U_4_11_out1 = (/*cliff*/sc_uint<32>)(
                                       GaussFilter_Add_2Ux1U_2U_4_11_in2.read()
                                        + 1ULL);
}
void GaussFilter::drive_mask_in1(){
  mask_in1 = GaussFilter_Add_4Ux2U_4U_4_10_out1.read();
}
// resource: GaussFilter_N_Mux_24_2_0_4
void GaussFilter::GaussFilter_N_Mux_24_2_0_4_12(){
  if ( i_rgb_m_stall_reg_full.read() ) {
    GaussFilter_N_Mux_24_2_0_4_12_out1 = i_rgb_m_stall_reg.read();
  } else {
    GaussFilter_N_Mux_24_2_0_4_12_out1 = i_rgb_data.read();
  }
}
// resource: mux_32bx2i0c
void GaussFilter::drive_GaussFilter_Mul_32Sx8U_32S_4_13_in2(){
  if ( gs_ctrl0.read() ) {
    GaussFilter_Mul_32Sx8U_32S_4_13_in2 = (sc_int<32> ) (s_reg_23.read());
  } else {
    GaussFilter_Mul_32Sx8U_32S_4_13_in2 = (sc_int<32> ) (
                                          GaussFilter_N_Mux_32_2_8_1_44_out1
                                          .read());
  }
}
// resource: mux_8bx2i0c
void GaussFilter::drive_GaussFilter_Mul_32Sx8U_32S_4_13_in1(){
  if ( gs_ctrl0.read() ) {
    GaussFilter_Mul_32Sx8U_32S_4_13_in1 = (sc_uint<8> ) (o_rgb_data.read()
                                          .range(23,16));
  } else {
    GaussFilter_Mul_32Sx8U_32S_4_13_in1 = (sc_uint<8> )
                                          GaussFilter_N_Mux_24_2_0_4_12_out1
                                          .read();
  }
}
// resource: GaussFilter_Mul_32Sx8U_32S_4  instance: GaussFilter_Mul_32Sx8U_32S_4_13
void GaussFilter::GaussFilter_Mul_32Sx8U_32S_4_13(){
  GaussFilter_Mul_32Sx8U_32S_4_13_out1 = GaussFilter_Mul_32Sx8U_32S_4_13_in2
                                         .read() * 
                                         GaussFilter_Mul_32Sx8U_32S_4_13_in1
                                         .read();
}
void GaussFilter::drive_GaussFilter_Mul_32Sx8U_32S_4_14_in1(){
  GaussFilter_Mul_32Sx8U_32S_4_14_in1 = (sc_uint<8> ) (
                                        GaussFilter_N_Mux_24_2_0_4_12_out1
                                        .read().range(15,8));
}
// resource: GaussFilter_Mul_32Sx8U_32S_4  instance: GaussFilter_Mul_32Sx8U_32S_4_14
void GaussFilter::GaussFilter_Mul_32Sx8U_32S_4_14(){
  GaussFilter_Mul_32Sx8U_32S_4_14_out1 = (sc_int<32> )
                                         GaussFilter_N_Mux_32_2_8_1_44_out1
                                         .read() * 
                                         GaussFilter_Mul_32Sx8U_32S_4_14_in1
                                         .read();
}
// resource: mux_32bx2i0c
void GaussFilter::drive_GaussFilter_Add_32Ux32U_32U_4_15_in1(){
  if ( gs_ctrl0.read() ) {
    GaussFilter_Add_32Ux32U_32U_4_15_in1 = (sc_uint<32> ) (s_reg_21.read());
  } else {
    GaussFilter_Add_32Ux32U_32U_4_15_in1 = (sc_uint<32> ) (s_reg_19.read());
  }
}
// resource: GaussFilter_Add_32Ux32U_32U_4  instance: GaussFilter_Add_32Ux32U_32U_4_15
void GaussFilter::GaussFilter_Add_32Ux32U_32U_4_15(){
  GaussFilter_Add_32Ux32U_32U_4_15_out1 = (/*cliff*/sc_uint<32>)((sc_uint<32> )
                                          GaussFilter_Mul_32Sx8U_32S_4_13_out1
                                          .read() + 
                                          GaussFilter_Add_32Ux32U_32U_4_15_in1
                                          .read());
}
// resource: GaussFilter_Add_32Ux32U_32U_4  instance: GaussFilter_Add_32Ux32U_32U_4_16
void GaussFilter::GaussFilter_Add_32Ux32U_32U_4_16(){
  GaussFilter_Add_32Ux32U_32U_4_16_out1 = (/*cliff*/sc_uint<32>)((sc_uint<32> )
                                          GaussFilter_Mul_32Sx8U_32S_4_14_out1
                                          .read() + (sc_uint<32> )s_reg_20
                                          .read());
}
// resource: GaussFilter_LessThan_2Ux2U_1U_4  instance: GaussFilter_LessThan_2Ux2U_1U_4_19
void GaussFilter::GaussFilter_LessThan_2Ux2U_1U_4_19(){
  GaussFilter_LessThan_2Ux2U_1U_4_19_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                            s_reg_22.read() < (sc_uint<2> )3ULL)
  ;
}
// resource: GaussFilter_LessThan_2Ux2U_1U_4  instance: GaussFilter_LessThan_2Ux2U_1U_4_20
void GaussFilter::GaussFilter_LessThan_2Ux2U_1U_4_20(){
  GaussFilter_LessThan_2Ux2U_1U_4_20_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                            s_reg_18.read() < (sc_uint<2> )3ULL)
  ;
}
// resource: mux_4bx2i0c
void GaussFilter::drive_GaussFilter_OrReduction_4U_1U_4_21_in1(){
  if ( gs_ctrl7.read() ) {
    GaussFilter_OrReduction_4U_1U_4_21_in1 = (sc_uint<4> )s_reg_20.read();
  } else {
    GaussFilter_OrReduction_4U_1U_4_21_in1 = (sc_uint<4> )s_reg_19.read();
  }
}
// resource: GaussFilter_OrReduction_4U_1U_4  instance: GaussFilter_OrReduction_4U_1U_4_21
void GaussFilter::GaussFilter_OrReduction_4U_1U_4_21(){
  GaussFilter_OrReduction_4U_1U_4_21_out1 = ((sc_uint<4>)GaussFilter_OrReduction_4U_1U_4_21_in1
                                            .read()).or_reduce();
}
// resource: mux_1bx2i0c
void GaussFilter::drive_GaussFilter_And_1Ux1U_1U_4_22_in1(){
  if ( gs_ctrl7.read() ) {
    GaussFilter_And_1Ux1U_1U_4_22_in1 = (sc_uint<1> ) (s_reg_20.read().range(31,
                                        31));
  } else {
    GaussFilter_And_1Ux1U_1U_4_22_in1 = (sc_uint<1> ) (s_reg_19.read().range(31,
                                        31));
  }
}
// resource: GaussFilter_And_1Ux1U_1U_4  instance: GaussFilter_And_1Ux1U_1U_4_22
void GaussFilter::GaussFilter_And_1Ux1U_1U_4_22(){
  GaussFilter_And_1Ux1U_1U_4_22_out1 = GaussFilter_OrReduction_4U_1U_4_21_out1
                                       .read() & 
                                       GaussFilter_And_1Ux1U_1U_4_22_in1.read();
}
// resource: mux_28bx2i0c
void GaussFilter::drive_GaussFilter_Add_28Sx1U_29S_4_23_in2(){
  if ( gs_ctrl7.read() ) {
    GaussFilter_Add_28Sx1U_29S_4_23_in2 = (sc_int<28> ) (((/*imp*/sc_uint<28> ) 
                                          s_reg_20.read().range(31,4)));
  } else {
    /* state8 */
    GaussFilter_Add_28Sx1U_29S_4_23_in2 = (sc_int<28> ) (((/*imp*/sc_uint<28> ) 
                                          s_reg_19.read().range(31,4)));
  }
}
// resource: GaussFilter_Add_28Sx1U_29S_4  instance: GaussFilter_Add_28Sx1U_29S_4_23
void GaussFilter::GaussFilter_Add_28Sx1U_29S_4_23(){
  GaussFilter_Add_28Sx1U_29S_4_23_out1 = (/*cliff*/sc_int<32>)(
                                         GaussFilter_Add_28Sx1U_29S_4_23_in2
                                         .read() + 
                                         GaussFilter_And_1Ux1U_1U_4_22_out1
                                         .read());
}
void GaussFilter::drive_GaussFilter_N_Mux_29_2_1_4_24_ctrl1(){
  GaussFilter_N_Mux_29_2_1_4_24_ctrl1 = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                                        GaussFilter_Add_28Sx1U_29S_4_23_out1
                                        .read().range(28,28)));
}
// resource: GaussFilter_N_Mux_29_2_1_4
void GaussFilter::GaussFilter_N_Mux_29_2_1_4_24(){
  if ( GaussFilter_N_Mux_29_2_1_4_24_ctrl1.read() ) {
    GaussFilter_N_Mux_29_2_1_4_24_out1 = 0ULL;
  } else {
    GaussFilter_N_Mux_29_2_1_4_24_out1 = (sc_uint<29> ) (
                                         GaussFilter_Add_28Sx1U_29S_4_23_out1
                                         .read());
  }
}
// resource: GaussFilter_LessThan_29Sx9S_1U_4  instance: GaussFilter_LessThan_29Sx9S_1U_4_25
void GaussFilter::GaussFilter_LessThan_29Sx9S_1U_4_25(){
  GaussFilter_LessThan_29Sx9S_1U_4_25_out1 = (/*imp*/sc_uint<1>)((sc_int<29> )
                                             GaussFilter_N_Mux_29_2_1_4_24_out1
                                             .read() < (sc_int<9> )255LL);
}
// resource: GaussFilter_N_Mux_8_2_2_4
void GaussFilter::GaussFilter_N_Mux_8_2_2_4_26(){
  if ( GaussFilter_LessThan_29Sx9S_1U_4_25_out1.read() ) {
    GaussFilter_N_Mux_8_2_2_4_26_out1 = (sc_uint<8> )
                                        GaussFilter_N_Mux_29_2_1_4_24_out1
                                        .read();
  } else {
    GaussFilter_N_Mux_8_2_2_4_26_out1 = 255ULL;
  }
}
// resource: mux_1bx2i2c
void GaussFilter::drive_r_busy(){
  if ( stall0.read() ) {
    r_busy = 1ULL;
  } else {
    if ( gs_ctrl10.read() ) {
      r_busy = 0ULL;
    } else {
      r_busy = 1ULL;
    }
  }
}
// resource: regr_en_sc_3
void GaussFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_3bx2i1c
void GaussFilter::drive_global_state_next(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 6ULL: 
    global_state_next = 1ULL;
    break;
  case 2ULL: 
    if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( GaussFilter_LessThan_2Ux2U_1U_4_20_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GaussFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 2ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GaussFilter::drive_gs_ctrl7(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl7 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl7 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl7 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GaussFilter::drive_gs_ctrl10(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl10 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl10 = 0ULL;
        break;
      case 1ULL: 
        gs_ctrl10 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: regr_sc_1
void GaussFilter::drive_fifo_dsel(){
  if ( (i_rst.read() == 0ULL) ) {
    fifo_dsel = 0ULL;
  } else {
    fifo_dsel = GaussFilter_gen_fifo_addr_alt0_4_43_out1.read();
  }
}
// resource: GaussFilter_gen_fifo_addr_alt0_4  instance: GaussFilter_gen_fifo_addr_alt0_4_43
void GaussFilter::GaussFilter_gen_fifo_addr_alt0_4_43_p4(){
  if ( GaussFilter_gen_fifo_addr_alt0_4_43_amtmp005.read() ) {
    GaussFilter_gen_fifo_addr_alt0_4_43_out1 = (fifo_dsel.read() + 1ULL);
  } else {
    if ( GaussFilter_gen_fifo_addr_alt0_4_43_amtmp004.read() ) {
      GaussFilter_gen_fifo_addr_alt0_4_43_out1 = fifo_dsel.read() - 1ULL;
    } else {
      GaussFilter_gen_fifo_addr_alt0_4_43_out1 = fifo_dsel.read();
    }
  }
}
// resource: GaussFilter_gen_fifo_addr_alt0_4  instance: GaussFilter_gen_fifo_addr_alt0_4_43
void GaussFilter::GaussFilter_gen_fifo_addr_alt0_4_43_p3(){
  GaussFilter_gen_fifo_addr_alt0_4_43_amtmp004 = !active_0.read() & ( !r_busy
                                                 .read() & fifo_dsel.read() );
}
// resource: GaussFilter_gen_fifo_addr_alt0_4  instance: GaussFilter_gen_fifo_addr_alt0_4_43
void GaussFilter::GaussFilter_gen_fifo_addr_alt0_4_43_p2(){
  GaussFilter_gen_fifo_addr_alt0_4_43_amtmp005 = active_0.read() & ( r_busy
                                                 .read() & !fifo_dsel.read() );
}
// resource: GaussFilter_N_Mux_32_2_8_1
void GaussFilter::GaussFilter_N_Mux_32_2_8_1_44(){
  if ( fifo_dsel.read() ) {
    GaussFilter_N_Mux_32_2_8_1_44_out1 = (sc_uint<32> ) (
                                         stall_fifo_1_stall_fifo_1_0.read());
  } else {
    GaussFilter_N_Mux_32_2_8_1_44_out1 = (sc_uint<32> ) (mask_out1.read());
  }
}
// resource: regr_32
void GaussFilter::drive_stall_fifo_1_stall_fifo_1_0(){
  stall_fifo_1_stall_fifo_1_0 = (sc_int<32> ) (
                                GaussFilter_N_Mux_32_2_8_4_45_out1.read());
}
// resource: GaussFilter_N_Mux_32_2_8_4
void GaussFilter::GaussFilter_N_Mux_32_2_8_4_45(){
  if ( active_0.read() ) {
    GaussFilter_N_Mux_32_2_8_4_45_out1 = (sc_uint<32> ) (mask_out1.read());
  } else {
    GaussFilter_N_Mux_32_2_8_4_45_out1 = (sc_uint<32> ) (
                                         stall_fifo_1_stall_fifo_1_0.read());
  }
}
// resource: mux_1bx2i2c
// resource: regr_sc_1
void GaussFilter::drive_active_0(){
  if ( (i_rst.read() == 0ULL) ) {
    active_0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      active_0 = 0ULL;
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      default:
        active_0 = 0ULL;
        break;
      case 0ULL: case 6ULL: 
        active_0 = 1ULL;
        break;
      case 2ULL: 
        if ( GaussFilter_LessThan_2Ux2U_1U_4_19_out1.read() ) {
          active_0 = 1ULL;
        } else {
          if ( GaussFilter_LessThan_2Ux2U_1U_4_20_out1.read() ) {
            active_0 = 1ULL;
          } else {
            active_0 = 0ULL;
          }
        }
        break;
      }
      break;
    }
  }
}
void GaussFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
               GaussFilter_gen_busy_r_4_42_out1.read().range(2,2)));
}
void GaussFilter::drive_i_rgb_m_data_is_valid(){
  i_rgb_m_data_is_valid = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                          GaussFilter_gen_busy_r_4_42_out1.read().range(1,1)));
}
// resource: GaussFilter_gen_busy_r_4  instance: GaussFilter_gen_busy_r_4_42
void GaussFilter::GaussFilter_gen_busy_r_4_42_p10(){
  GaussFilter_gen_busy_r_4_42_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)
                                     ((sc_bv<1>)(
                                     GaussFilter_gen_busy_r_4_42_gnew_busy
                                     .read()), 
                                     (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                     (sc_bv<1>)(GaussFilter_gen_busy_r_4_42_gdiv
                                     .read()), 
                                     (sc_bv<1>)(GaussFilter_gen_busy_r_4_42_gen_busy_i_rgb_m_data_is_invalid_next
                                     .read())) ))) ));
}
// resource: GaussFilter_gen_busy_r_4  instance: GaussFilter_gen_busy_r_4_42
void GaussFilter::GaussFilter_gen_busy_r_4_42_p9(){
  GaussFilter_gen_busy_r_4_42_gen_busy_i_rgb_m_data_is_invalid_next = ~(sc_uint<1>)GaussFilter_gen_busy_r_4_42_gdiv
                                                                      .read();
}
// resource: GaussFilter_gen_busy_r_4  instance: GaussFilter_gen_busy_r_4_42
void GaussFilter::GaussFilter_gen_busy_r_4_42_p8(){
  GaussFilter_gen_busy_r_4_42_gdiv = (sc_uint<1> ) (i_rgb_vld.read() & !
                                     GaussFilter_gen_busy_r_4_42_gnew_req.read()
                                      | (sc_uint<1> )i_rgb_m_stall_reg_full
                                     .read());
}
// resource: GaussFilter_gen_busy_r_4  instance: GaussFilter_gen_busy_r_4_42
void GaussFilter::GaussFilter_gen_busy_r_4_42_p7(){
  GaussFilter_gen_busy_r_4_42_gnew_busy = (sc_uint<1> ) (
                                          GaussFilter_gen_busy_r_4_42_gnew_req
                                          .read() | (sc_uint<1> )
                                          i_rgb_m_stall_reg_full.read());
}
// resource: GaussFilter_gen_busy_r_4  instance: GaussFilter_gen_busy_r_4_42
void GaussFilter::GaussFilter_gen_busy_r_4_42_p6(){
  GaussFilter_gen_busy_r_4_42_gnew_req = (sc_uint<1> ) (i_rgb_m_busy_req_0
                                         .read() & ( i_rgb_m_unvalidated_req
                                         .read() | (sc_uint<1> )i_rgb_vld.read()
                                          ));
}
// resource: regr_ss_1
void GaussFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (GaussFilter_N_Muxb_1_2_3_4_4_out1
                              .read());
  }
}
// resource: GaussFilter_N_Muxb_1_2_3_4
void GaussFilter::GaussFilter_N_Muxb_1_2_3_4_4(){
  if ( i_rgb_m_busy_req_0.read() ) {
    GaussFilter_N_Muxb_1_2_3_4_4_out1 = (sc_uint<1> ) (i_rgb_m_unvalidated_req
                                        .read());
  } else {
    GaussFilter_N_Muxb_1_2_3_4_4_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
// resource: regr_en_24
void GaussFilter::drive_i_rgb_m_stall_reg(){
  switch( (sc_uint<1>)(GaussFilter_And_1Ux1U_1U_4_7_out1.read()) ) {
  case 1ULL: 
    i_rgb_m_stall_reg = i_rgb_data.read();
    break;
  case 0ULL: 
    break;
  }
}
// resource: GaussFilter_Not_1U_1U_4  instance: GaussFilter_Not_1U_1U_4_5
void GaussFilter::GaussFilter_Not_1U_1U_4_5(){
  GaussFilter_Not_1U_1U_4_5_out1 = !i_rgb_m_stall_reg_full.read();
}
// resource: GaussFilter_And_1Ux1U_1U_4  instance: GaussFilter_And_1Ux1U_1U_4_6
void GaussFilter::GaussFilter_And_1Ux1U_1U_4_6(){
  GaussFilter_And_1Ux1U_1U_4_6_out1 = i_rgb_m_data_is_valid.read() & (
                                      sc_uint<1>)stall0.read();
}
// resource: GaussFilter_And_1Ux1U_1U_4  instance: GaussFilter_And_1Ux1U_1U_4_7
void GaussFilter::GaussFilter_And_1Ux1U_1U_4_7(){
  GaussFilter_And_1Ux1U_1U_4_7_out1 = GaussFilter_And_1Ux1U_1U_4_6_out1.read()
                                       & GaussFilter_Not_1U_1U_4_5_out1.read();
}
// resource: regr_sc_1
void GaussFilter::drive_i_rgb_m_stall_reg_full(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_stall_reg_full = 0ULL;
  } else {
    i_rgb_m_stall_reg_full = (sc_uint<1> ) (GaussFilter_And_1Ux1U_1U_4_40_out1
                             .read());
  }
}
// resource: GaussFilter_And_1Ux1U_1U_4  instance: GaussFilter_And_1Ux1U_1U_4_40
void GaussFilter::GaussFilter_And_1Ux1U_1U_4_40(){
  GaussFilter_And_1Ux1U_1U_4_40_out1 = i_rgb_m_data_is_valid.read() & (
                                       sc_uint<1>)stall0.read();
}
void GaussFilter::drive_o_rgb_vld(){
  o_rgb_vld = (sc_uint<1> ) (GaussFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: GaussFilter_Or_1Ux1U_1U_4  instance: GaussFilter_Or_1Ux1U_1U_4_2
void GaussFilter::GaussFilter_Or_1Ux1U_1U_4_2(){
  GaussFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_rgb_m_unacked_req.read()
                                      | (sc_uint<1>)
                                     GaussFilter_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void GaussFilter::drive_o_rgb_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_rgb_m_unacked_req = 0ULL;
  } else {
    o_rgb_m_unacked_req = (sc_uint<1> ) (GaussFilter_And_1Ux1U_1U_4_39_out1
                          .read());
  }
}
// resource: GaussFilter_And_1Ux1U_1U_4  instance: GaussFilter_And_1Ux1U_1U_4_39
void GaussFilter::GaussFilter_And_1Ux1U_1U_4_39(){
  GaussFilter_And_1Ux1U_1U_4_39_out1 = o_rgb_busy.read() & o_rgb_vld.read();
}
// resource: GaussFilter_Xor_1Ux1U_1U_1  instance: GaussFilter_Xor_1Ux1U_1U_1_1
void GaussFilter::GaussFilter_Xor_1Ux1U_1U_1_1(){
  GaussFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (o_rgb_m_req_m_trig_req
                                      .read() ^ o_rgb_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void GaussFilter::drive_o_rgb_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_rgb_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_rgb_m_req_m_prev_trig_req = o_rgb_m_req_m_trig_req.read();
  }
}
// resource: GaussFilter_Not_1U_1U_1  instance: GaussFilter_Not_1U_1U_1_3
void GaussFilter::GaussFilter_Not_1U_1U_1_3(){
  GaussFilter_Not_1U_1U_1_3_out1 = !o_rgb_m_req_m_trig_req.read();
}
