// Generated by stratus_hls 19.12-s100  (91710.131054)
// Tue Apr 12 21:25:06 2022
// from ../GaussFilter.cpp
#include "GaussFilter_ROM_9X32_mask.h"

struct GaussFilter_ROM_9X32_mask;
GaussFilter_ROM_9X32_mask::GaussFilter_ROM_9X32_mask(sc_module_name name) : sc_module(name) 
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,mask()
{
  CYN_ROM_INIT( sc_uint<32> , mask, ENUMS::CYN_HEX, "bdw_work/modules/GaussFilter/DPA/GaussFilter_ROM_9X32_mask_0.memh", "initialize GaussFilter_ROM_9X32_mask" ); 
  SC_METHOD(GaussFilter_ROM_9X32_mask_mask_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void GaussFilter_ROM_9X32_mask::GaussFilter_ROM_9X32_mask_mask_thread_1(){
  if ( (/*imp*/sc_uint<1>)(in1.read() < ((/*imp*/sc_uint<4> )(9ULL))) ) {
    out1 = (sc_uint<32> ) ((mask)[in1.read()]);
  } 
}
